### ISSUE TITLE
java.lang.RuntimeException: Exception while binding MockServer to port

### ISSUE THREAD

**Issue by dzmitrykashlach** [jamesdbloom/mockserver#202] opened 2015-11-25 13:08 UTC
It seems to be a duplicate for
https://github.com/jamesdbloom/mockserver/issues/150
but it is present with version 3.10.2

java.lang.RuntimeException: Exception while binding MockServer to port 1234
	at org.mockserver.mockserver.MockServer.bindToPorts(MockServer.java:108)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:61)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:20)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:29)

I've tried to build mockserver with fixies mentioned in #150 but got OOM.
What can be checked to solve this? Thanks.

**Comment by gregorymaertens** [comment] 2015-12-21 18:55
I have the same issue (also on 3.10.2). Did you solve it?

**Comment by dzmitrykashlach** [comment] 2016-01-15 15:17
no, still having it.

**Comment by jamesdbloom** [comment] 2016-02-18 18:23
I'm not quiet sure what bug exactly you're seeing, perhaps you could provide some more details? 

MockServer throws an error if it can't bind to a port that is already in use, that's because the operating system won't allow two applications to bind to the same port because it wouldn't know which network packets to send to which application.  

#150 referred to a different issue where MockServer blocked when there was a port binding error instead of throwing an exception.  However that has been fixed as the following code and output demonstrates:

```java
public static void main(String[] args) {
    ClientAndServer.startClientAndServer(1234);    // success - server started
    try {
        ClientAndServer.startClientAndServer(1234);    // java.net.BindException in log - call never returns!
    } catch (Exception e) {
        System.out.println("e = " + e);
    }
    System.out.println("passed error bind error");
}
```

This produces the following output:

```bash
18:18:52.640 [MockServer thread for port: 1234] INFO  org.mockserver.mockserver.MockServer - MockServer started on port: 1234
Exception in thread "MockServer thread for port: 1234" java.lang.RuntimeException: Exception while binding MockServer to port 1234
	at org.mockserver.mockserver.MockServer$2.run(MockServer.java:101)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:414)
	at sun.nio.ch.Net.bind(Net.java:406)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	... 1 more
e = java.lang.RuntimeException: Exception while binding MockServer to port 1234
passed error bind error
```

**Comment by jamesdbloom** [comment] 2016-03-04 22:14
I am closing this issue as I believe there is no issue, if you have evidence of an issue please reopen the ticket.

**Closed by jamesdbloom** 2016-03-04 22:14 UTC

**Comment by avvdp** [comment] 2016-06-06 00:46
I'm facing same issue.. please find below exception stack.. 
Forking command line: cmd.exe /X /C "C:\jdk1.8.0_45\jre\bin\java -jar C:\Users\test\git\mockserver\mockserver-netty\target\surefire\surefirebooter671574389436600865.jar C:\Users\test\git\mockserver\mockserver-netty\target\surefire\surefire1793171225145625831tmp C:\Users\test\git\mockserver\mockserver-netty\target\surefire\surefire_18870529570318141551tmp"
Running org.mockserver.integration.mockserver.ClientAndServerIntegrationTest
Exception in thread "MockServer thread for port: 55094" java.lang.RuntimeException: Exception while binding MockServer to port 55094
	at org.mockserver.mockserver.MockServer$2.run(MockServer.java:103)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)

**Comment by pochemuto** [comment] 2020-02-06 14:36
I have same issue

```
[fail] ru.yandex.ci.client.sandbox.SandboxClientTest::resourceInfo() [default-darwin-x86_64-debug] (0.00 s)
java.lang.RuntimeException: Exception while binding MockServer to port 61949
	at org.mockserver.lifecycle.LifeCycle.bindPorts(LifeCycle.java:194)
	at org.mockserver.lifecycle.LifeCycle.bindServerPorts(LifeCycle.java:158)
	at org.mockserver.mockserver.MockServer.createServerBootstrap(MockServer.java:116)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:49)
	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:39)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:19)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:34)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:30)
	at org.mockserver.junit.jupiter.MockServerExtension.instantiateClient(MockServerExtension.java:62)
	at org.mockserver.junit.jupiter.MockServerExtension.beforeAll(MockServerExtension.java:51)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:355)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:355)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at
..[truncated]..
:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
		... 26 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I'm not sure but can socket be not released after findFreePorts execution? 
https://github.com/mock-server/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/socket/PortFactory.java#L33

Issue is reproducible

**Comment by jamesdbloom** [comment] 2020-02-07 05:30
@pochemuto your issue is likely unrelated to the original issue that caused this ticket, I have however made a small change to reduce the chance of a problem in your case.  This is now in the SNAPSHOT and will be in the next release.

**Comment by Rama000777** [comment] 2020-10-19 09:24
@jamesdbloom is the port binding issue resolved, still with jenkins parallel builds it is still failing.

**Comment by almiskea** [comment] 2021-09-03 18:11
I had this issue multiple times,

one of the most recent times was because Spring optimization made tests run in parallel
so, when I auto-generated the port it worked so you have multiple solutions

the solutions:-
1- randomly generate ports (bad solution) it works 99% of the time
2- make a unique port per tests (not so convenient)
3- disable running the tests in parallel
4- find a way to generate new port numbers that do not conflict with the previous ones for each test
