### ISSUE TITLE
Java lang NullPointerException While running mock-server proxy

### ISSUE THREAD

**Issue by nyochai** [jamesdbloom/mockserver#590] opened 2019-02-12 09:43 UTC
I am running mock-server on port 1092, and when i try browsing to a number of sites including mcdonalds.com, ekwb.com and more I get the following exception:

2019-02-12 11:06:44,852 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:44,993 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:45,106 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:45,133 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:45,151 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:45,159 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:45,172 INFO o.m.m.HttpStateHandler no active expectations
2019-02-12 11:06:45,430 ERROR o.m.m.HttpStateHandler io.netty.handler.codec.DecoderException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.mockserver.mock.action.ActionHandler$11.run(ActionHandler.java:199) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.mockserver.client.netty.codec.mappers.FullHttpResponseToMockServerResponse.setCookies(FullHttpResponseToMockServerResponse.java:52) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.mockserver.client.netty.codec.mappers.FullHttpResponseToMockServerResponse.mapMockServerResponseToFullHttpResponse(FullHttpResponseToMockServerResponse.java:24) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.mockserver.client.netty.codec.MockServerResponseDecoder.decode(MockServerResponseDecoder.java:17) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.mockserver.client.netty.codec.MockServerResponseDecoder.decode(MockServerResponseDecoder.java:13) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[mockserver-netty-5.5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	... 44 common frames omitted
2019-02-12 11:06:45,436 INFO o.m.m.HttpStateHandler returning response:

	{
	  "statusCode" : 204,
	  "reasonPhrase" : "No Content",
	  "headers" : {
	    "Cache-Control" : [ "no-cache, must-revalidate" ],
	    "Pragma" : [ "no-cache" ],
	    "Expires" : [ "Fri, 01 Jan 1990 00:00:00 GMT" ],
	    "Access-Control-Allow-Origin" : [ "*" ],
	    "X-MSEdge-Ref" : [ "Ref A: 5AD066F64D4C4EC48E9B7D2A7B0DBD0B Ref B: FRAEDGE0817 Ref C: 2019-02-12T09:06:45Z" ],
	    "Date" : [ "Tue, 12 Feb 2019 09:06:44 GMT" ],
	    "content-length" : [ "0" ]
	  }
	}

 for forwarded request

 in json:

	{
	  "method" : "GET",
	  "path" : "/action/0",
	  "queryStringParameters" : {
	    "ti" : [ "5528047" ],
	    "Ver" : [ "2" ],
	    "mid" : [ "a27b410e-0fca-af69-cbcb-359c91a593ad" ],
	    "pi" : [ "1200101525" ],
	    "lg" : [ "en-US" ],
	    "sw" : [ "1920" ],
	    "sh" : [ "1080" ],
	    "sc" : [ "24" ],
	    "tl" : [ "McDonald's: Burgers, Fries & More. Quality Ingredients." ],
	    "p" : [ "https://www.mcdonalds.com/us/en-us.html" ],
	    "r" : [ "" ],
	    "lt" : [ "5544" ],
	    "evt" : [ "pageLoad" ],
	    "msclkid" : [ "N" ],
	    "rn" : [ "697399" ]
	  },
	  "headers" : {
	    "Host" : [ "bat.bing.com" ],
	    "Connection" : [ "keep-alive" ],
	    "User-Agent" : [ "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" ],
	    "Accept" : [ "image/webp,image/apng,image/*,*/*;q=0.8" ],
	    "Referer" : [ "https://www.mcdonalds.com/us/en-us.html" ],
	    "Accept-Encoding" : [ "gzip, deflate, br" ],
	    "Accept-Language" : [ "en-US,en;q=0.9,he;q=0.8" ],
	    "Cookie" : [ "MUID=B8FCEAFC156D4EDBA544BDA32D8466A5; MUIDB=B8FCEAFC156D4EDBA544BDA32D8466A5" ],
	    "content-length" : [ "0" ]
	  },
	  "cookies" : {
	    "MUID" : "B8FCEAFC156D4EDBA544BDA32D8466A5",
	    "MUIDB" : "B8FCEAFC156D4EDBA544BDA32D8466A5"
	  },
	  "keepAlive" : true,
	  "secure" : true
	}

**Comment by nyochai** [comment] 2019-02-13 12:46
Update - after looking in to this, found that this exception happens specifically when sites try to connect to facebook:

Request URL: https://www.facebook.com/tr/?id=986079768127815&ev=PageView&dl=https%3A%2F%2Fwww.ekwb.com%2F&rl=&if=false&ts=1550061855543&sw=1920&sh=1080&v=2.8.40&r=stable&ec=0&o=30&fbp=fb.1.1549962166493.2035024667&it=1550061853719&coo=false&rqm=GET 

The requests gets stuck pending and mockserver throws the exception above

**Comment by jamesdbloom** [comment] 2019-02-24 06:50
I can not reproduce this issue with the latest code can you please tell me how you are proxying your request and which version of MockServer you are using.

**Comment by nyochai** [comment] 2019-02-24 07:50
I'm using mock-server version 5.5.2 and using it to record all requests & responses through https proxy

**Comment by jamesdbloom** [comment] 2019-03-27 08:02
I am closing this issue as can't reproduce and not enough details provided to progress.

**Closed by jamesdbloom** 2019-03-27 08:02 UTC
Labels: bug, need_more_information
