### ISSUE TITLE
Error deserializing body request in mockserver

### ISSUE THREAD

**Issue by ignaciotcrespo** [jamesdbloom/mockserver#414] opened 2018-01-15 18:30 UTC
I created an expectation POST without a specific body, and I am sending this http POST with the following body

```
{"method":"any","service":"any_service", "parameters": { "applicationName":"name","password":"pwd","username":"user" } }
```

but the request doesn't work due to I get an exception in the mockserver

```
java.lang.RuntimeException: Unexpected token: "VALUE_STRING" id: "6" text: "name
        at org.mockserver.client.serialization.deserializers.collections.KeysToMultiValuesDeserializer.deserializeObject(KeysToMultiValuesDeserializer.java:56) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.client.serialization.deserializers.collections.KeysToMultiValuesDeserializer.deserialize(KeysToMultiValuesDeserializer.java:35) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at org.mockserver.client.serialization.deserializers.collections.KeysToMultiValuesDeserializer.deserialize(KeysToMultiValuesDeserializer.java:22) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
        at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1723) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
```

any idea why this json can not be processed? Looks very simple and correct.

**Comment by ignaciotcrespo** [comment] 2018-01-15 19:12
my mistake, I was sending the request to the proxy instead of the mock server

**Comment by ignaciotcrespo** [comment] 2018-01-16 09:38
Reopened, the exception happens in both mock server and proxy server.

**Comment by jamesdbloom** [comment] 2018-01-16 23:01
I'll take a look

**Comment by ignaciotcrespo** [comment] 2018-01-17 18:05
thanks!

BTW I tried older versions and it doesn't happen on v5.1.1 and older

**Comment by jamesdbloom** [comment] 2018-01-19 08:57
I have found the bug and fixed the issue.

It was caused by trying to serialise the body into a BodyDTO, which is a fallback to support the matching for /clear and /retrieve endpoint where an expectation is submitted in the body.

I am currently in the middle of a number of major improvements, such as adding a UI and better performance for load testing.  Therefore is may be a few weeks before I can do a release.  However in the mean time you can use the latest SNAPSHOT version, [as described on the website](http://mock-server.com/where/maven_central.html#sonatype_snapshot).

I'm going to close this ticket as it is now fixed and will be release in the next release (which will be a major version change due to a few minor breaking changes in the API).

**Closed by jamesdbloom** 2018-01-19 08:57 UTC
Labels: bug

**Comment by ignaciotcrespo** [comment] 2018-01-19 09:26
Thanks for the fix! Will try the snapshot 👍
