### ISSUE TITLE
Content-Length Default Value Problem

### ISSUE THREAD

**Issue by igalbenardete** [jamesdbloom/mockserver#92] opened 2015-01-27 13:34 UTC
In my program I have a case where th Content-Length received from a server can be -1 which means corrupted file or some problem. But when I am testing with MockServer, it does not allow me to change or remove the content-length header. It adds to the list as a second value even though I do not send  any body. Is there a way to change this value ? or create a response where the Content-Length header is removed ?

**Comment by jamesdbloom** [comment] 2015-02-12 08:40
The problem is Content-Length is part of the HTTP specification so if I remove it from responses then the MockServer will return in valid HTTP responses.  I could potentially add a feature where if the Content-Length is already specified in the mock response I don't add a Content-Length header or update the existing one that way you could mock any Content-Length header.  I guess you only want this for the MockServer and not for the proxy?

**Comment by jamesdbloom** [comment] 2015-02-12 11:39
I've committed a fix so I'm closing this ticket, once I've fixed a couple more bugs I'll do a full release.

**Closed by jamesdbloom** 2015-02-12 11:39 UTC
