### ISSUE TITLE
"response body with literal only" REST API example causes 400 Bad Request error

### ISSUE THREAD

**Issue by brianhv** [jamesdbloom/mockserver#575] opened 2018-12-26 17:22 UTC
I ran the server using `docker run -d -p 1080:1080 jamesdbloom/mockserver`. I then tried to run the curl command under [Creating Expectations](http://www.mock-server.com/mock_server/creating_expectations.html) -> "Response Action Code Examples" -> "response literal with body only."

```
%curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
    "httpResponse": {
        "body": "some_response_body"
    }
}'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1080 (#0)
> PUT /mockserver/expectation HTTP/1.1
> Host: localhost:1080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 68
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 68 out of 68 bytes
< HTTP/1.1 400 Bad Request
< access-control-allow-origin: *
< access-control-allow-methods: CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE
< access-control-allow-headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization
< access-control-expose-headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization
< access-control-max-age: 300
< x-cors: MockServer CORS support enabled by default, to disable ConfigurationProperties.enableCORSForAPI(false) or -Dmockserver.enableCORSForAPI=false
< version: 5.5.0
< connection: keep-alive
< content-length: 0
<
* Connection #0 to host localhost left intact
```

I tried the example under "Request Matcher Code Examples" -> "match request by path only twice" and it succeeded, so things seem to be running OK otherwise.

**Comment by jamesdbloom** [comment] 2018-12-30 08:11
I can see what the issue is I'll fix it shortly

**Comment by jamesdbloom** [comment] 2018-12-30 13:38
this is now fixed, the issue was caused by a null pointer due to a merged PR

**Closed by jamesdbloom** 2018-12-30 13:38 UTC
Labels: bug, in progress

**Comment by agent019** [comment] 2019-04-12 20:39
For anyone still using the 5.5.1 jar and looking to figure out how to resolve this, you can fix it by adding an empty httpRequest object to your expectation creation json:
```json
{
    "httpRequest": { }      // <-- Add this 
    "httpResponse":{
        // Response body here
    }
}
