### ISSUE TITLE
Some tests require English as system's language

### ISSUE THREAD

**Issue by SchulteMarkus** [jamesdbloom/mockserver#350] opened 2017-06-27 08:37 UTC
Greetings from germany!

    $ echo $LANG
        de_DE.UTF-8

Some tests do not run on my machine. They seem to dependent on the system's language being English.

```
Failed tests: 
  ClientAndServerIntegrationTest>AbstractMockServerNettyIntegrationTest.shouldReturnResponseWithConnectionOptionsAndCloseSocketAndSuppressContentLength:466 
Expected: (a string containing "Broken pipe" or a string containing "Connection reset" or a string containing "Protocol wrong type")
     but: was "Datenübergabe unterbrochen (broken pipe) (Write failed)"
  MockServerAutoAllocatedPortIntegrationTest>AbstractMockServerNettyIntegrationTest.shouldReturnResponseWithConnectionOptionsAndCloseSocketAndSuppressContentLength:466 
Expected: (a string containing "Broken pipe" or a string containing "Connection reset" or a string containing "Protocol wrong type")
     but: was "Datenübergabe unterbrochen (broken pipe) (Write failed)"
  MockServerIntegrationTest>AbstractMockServerNettyIntegrationTest.shouldReturnResponseWithConnectionOptionsAndCloseSocketAndSuppressContentLength:466 
Expected: (a string containing "Broken pipe" or a string containing "Connection reset" or a string containing "Protocol wrong type")
     but: was "Datenübergabe unterbrochen (broken pipe) (Write failed)"
  MockServerMultiplePortIntegrationTest>AbstractMockServerNettyIntegrationTest.shouldReturnResponseWithConnectionOptionsAndCloseSocketAndSuppressContentLength:466 
Expected: (a string containing "Broken pipe" or a string containing "Connection reset" or a string containing "Protocol wrong type")
     but: was "Datenübergabe unterbrochen (broken pipe) (Write failed)"
  MockServerRuleIntegrationTest>AbstractMockServerNettyIntegrationTest.shouldReturnResponseWithConnectionOptionsAndCloseSocketAndSuppressContentLength:466 
Expected: (a string containing "Broken pipe" or a string containing "Connection reset" or a string containing "Protocol wrong type")
     but: was "Datenübergabe unterbrochen (broken pipe) (Write failed)"
```

**Comment by jamesdbloom** [comment] 2017-06-27 09:05
Is that the only test that does that?  It look's like the error messages from Netty or JVM are internationalized so I'll need to take account of that.

When I get a chance I resolve that as in theory it should be fairly straight forward to internationalize the test in the same way the error messages are.

**Comment by SchulteMarkus** [comment] 2017-06-27 09:08
It seemed to be the only test, yes. But I cannot guarantee, as the build is broken right now.

**Comment by jamesdbloom** [comment] 2017-06-30 14:29
I can't reproduce this.  I am running the build with both LANG and set to de_DE and Java system properties setting default locale to de_DE as follows:

```bash
export LANG=de_DE.UTF-8
export MAVEN_OPTS="$MAVEN_OPTS -XX:MaxPermSize=1024m -Xmx2048m -Duser.language=de -Duser.country=DE"
```

Then:

`mvn -version`

Outputs:

```bash
requires maven version 3.2.5 so that Java 1.6 can be used, i.e. brew install maven@3.2
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/Cellar/maven@3.2/3.2.5/libexec
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: de_DE, platform encoding: MacRoman
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
```

But the build still passes for me without issue.  Is there a special version of Java you have installed?

**Comment by SchulteMarkus** [comment] 2017-06-30 14:30
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by jamesdbloom** [comment] 2017-06-30 15:20
I can see that localization of these error messages was clearly introduced in Java 1.8.  Now I've switched to Java 1.8 I get the same errors.

**Comment by jamesdbloom** [comment] 2017-06-30 16:16
This should now be resolved so please re-test.  I'm closing this ticket but please re-open if you find the issue has not been fixed.

**Closed by jamesdbloom** 2017-06-30 16:16 UTC

**Comment by SchulteMarkus** [comment] 2017-07-05 07:35
Fixed!
