### ISSUE TITLE
support for emojis is broken as of version 3.9.16

### ISSUE THREAD

**Issue by jolivares** [jamesdbloom/mockserver#162] opened 2015-07-31 10:14 UTC
Trying to use an emoji as response body won't work. It seems some encoding problem has been introduced.

It works ok with 3.9.15.

This is a simple test case to reproduce the problem:

``` java


import static org.junit.Assert.assertEquals;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import org.junit.Test;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.model.Header;

public class EmojiTest {

    @Test
    public void test() throws Exception {
        ClientAndServer mockServer = new ClientAndServer(9090);
        String expected = "\uD83D\uDE04";

        mockServer.when(request().withMethod("GET").withPath("/emoji")).respond(
                response().withStatusCode(200).withHeader(new Header("Content-Type", "tex/plain")).withBody(expected));

        URL obj = new URL("http://127.0.0.1:9090/emoji");
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
        BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));

        StringBuilder actual = new StringBuilder();
        String line;
        while ((line = in.readLine()) != null) {
            actual.append(line);
        }

        assertEquals(expected, actual.toString());
    }
}
```

**Comment by jamesdbloom** [comment] 2015-08-05 10:30
As soon as I get a chance I'll look into this, likely in the next week or so.

**Comment by jolivares** [comment] 2015-09-14 15:23
This problem seems to be related to the default charset which mockserver uses: ```CharsetUtil.ISO_8859_1```. It could make sense for ```text/plain```, but it also uses ```CharsetUtil.ISO_8859_1``` as default charset for ```application/json``` which I think is wrong since default encoding in this case is ```utf-8```

The following test fails unless I add the charset to the Content-Type header:
```` java
	@Test
	public void test_json() throws Exception {
		ClientAndServer mockServer = new ClientAndServer(9090);
		String expected = "{\"field\":\"\uD83D\uDE04\"}";

		mockServer.when(request().withMethod("GET").withPath("/emoji")).respond(response().withStatusCode(200)
				.withHeader(new Header("Content-Type", "application/json")).withBody(expected));

		URL obj = new URL("http://127.0.0.1:9090/emoji");
		HttpURLConnection con = (HttpURLConnection) obj.openConnection();
		BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));

		StringBuilder actual = new StringBuilder();
		String line;
		while ((line = in.readLine()) != null) {
			actual.append(line);
		}

		assertEquals(expected, actual.toString());
	}
```

**Comment by marklieberman** [comment] 2016-03-31 19:05
Not sure if this is related, or should be created as a separate issue. I have a JsonBody request that I am mocking out that would never match on 3.10.4, even though it absolutely should have matched. I rolled back to 3.9.15 after reading this issue and it started matching. I tried many variations using fields like api_token, so its not specific to the JSON structure. I also manually asserted that it matches using JSONAssert. So, it is definitely something in MockServer.
```
request().withMethod("POST").withPath("/analytics/segmentWidget")
  .withBody(new JsonBody("{\"group_bys\":[\"P_ORDERS_AVG_INTERVAL\",\"P_ORDERS_INTERVAL\",\"P_ORDER_COUNT\",\"P_LAST_ORDER_INTERVAL\"]}"));
```
-->
```
 "body" : {
	    "charset" : "UTF-8",
	    "type" : "STRING",
	    "string" : "{\"api_token\":\"ab8a4045-6481-41c0-9a7c-e283d41f9c6b\",\"filters\":[],\"fetch_graph\":false,\"group_bys\":[\"P_ORDERS_AVG_INTERVAL\",\"P_ORDERS_INTERVAL\",\"P_ORDER_COUNT\",\"P_LAST_ORDER_INTERVAL\"],\"length\":1,\"order\":[],\"draw\":1,\"start\":0,\"columns\":[],\"search\":{\"regex\":false,\"value\":\"\"},\"fetch_counts\":false}"
	  }
	}

 did not match expectation:

	{
	  "method" : "POST",
	  "path" : "/analytics/segmentWidget",
	  "body" : {
	    "charset" : "UTF-8",
	    "type" : "JSON",
	    "json" : "{\"api_token\":\"ab8a4045-6481-41c0-9a7c-e283d41f9c6b\"}"
	  }
	}

 because:

	method matches = true
	path matches = true
	query string parameters match = true
	body matches = false
	headers match = true
	cookies match = true
	keep-alive matches = true
	ssl matches = true

```

**Comment by jamesdbloom** [comment] 2017-05-22 07:23
For the JSON issue you mentioned can be please raise a separate issue.

For the Emoji issue the problem is there is no charset specified.  The Emoji characters you have specified are not available in the default HTTP character set (ISO/IEC 8859-1), so instead a `?` appears.  If you specify the charset by adding this to the content type header, as below, then the test passes:

```java
import static org.junit.Assert.assertEquals;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import org.junit.Test;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.model.Header;

public class EmojiTest {

    @Test
    public void test() throws Exception {
        ClientAndServer mockServer = new ClientAndServer(9090);
        String expected = "\uD83D\uDE04";

        mockServer.when(request().withMethod("GET").withPath("/emoji")).respond(
                response().withStatusCode(200).withHeader(new Header("Content-Type", "tex/plain; charset=utf-8")).withBody(expected));

        URL obj = new URL("http://127.0.0.1:9090/emoji");
        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
        BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));

        StringBuilder actual = new StringBuilder();
        String line;
        while ((line = in.readLine()) != null) {
            actual.append(line);
        }

        assertEquals(expected, actual.toString());
    }
}
```

I am closing this ticket because it is now working, particularly with the merged PR from @diwakarbhatt123.

**Closed by jamesdbloom** 2017-05-22 07:23 UTC
Labels: bug, in progress
