### ISSUE TITLE
Buggy scenario

### ISSUE THREAD

**Issue by khanh-nguyen** [jamesdbloom/mockserver#143] opened 2015-06-04 16:37 UTC
I want to have a scenario that query to an end point returns `401, 401` followed by infinite `200`. Here're the expectations I stubbed in sequence.
```
{
    httpRequest: {
        method: 'GET',
        path: '/path/to/x'
    },
    httpResponse: {
        statusCode: 401
    },
    times: {
        remainingTimes: 2,
        unlimited: false
    }
}

{
    httpRequest: {
        method: 'GET',
        path: '/path/to/x'
    },
    httpResponse: {
        statusCode: 200
    },
    times: {
    		unlimited: true
		}    		
}
``` 
As the result, after getting 2 `401` and 1 `200`, I get `404`.
However, if I only stub this
```
{
    httpRequest: {
        method: 'GET',
        path: '/path/to/x'
    },
    httpResponse: {
        statusCode: 200
    },
    times: {
    		unlimited: true
		}    		
}
```
then, I'm able to get `200` infinitely.

**Comment by jamesdbloom** [comment] 2015-06-05 05:54
I'll take a look and get back on this.

**Comment by jamesdbloom** [comment] 2015-06-05 07:37
This may be caused by two separate features overlapping but I need to double check this and add some tests to cover this exact scenario

**Comment by jamesdbloom** [comment] 2015-06-05 15:26
This should be fixed in the current 3.9.16-SNAPSHOT and will be released in the next couple of days

**Closed by jamesdbloom** 2015-06-05 15:26 UTC

**Comment by khanh-nguyen** [comment] 2015-06-06 04:10
Yes, it's working correctly now. You're awesome, @jamesdbloom. Thanks a lot.
