### ISSUE TITLE
Expectation callback mixes up responses or fails to answer some simultaneous requests

### ISSUE THREAD

**Issue by andpab** [jamesdbloom/mockserver#427] opened 2018-02-01 14:36 UTC
This is probably the same issue as reported in https://github.com/jamesdbloom/mockserver/issues/342

When configuring the mock server with a callback for a given HTTP path and then sending simultaneous requests, some requests will not be answered or the answers will be mixed up.

I've attached the below code wrapped in a simple Maven project for your convenience.

[mockserver-concurrency-failure.zip](https://github.com/jamesdbloom/mockserver/files/1685862/mockserver-concurrency-failure.zip)

`package org.mockserver.concurrency;

import java.net.InetSocketAddress;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockserver.client.netty.NettyHttpClient;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.model.HttpResponse;

import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

public class MockServerConcurrencyTest {

    private static final int SERVER_PORT = 11005;
    private static final InetSocketAddress SERVER_ADDRESS = new InetSocketAddress("localhost", SERVER_PORT);
    private static final String ECHO_PATH = "/my/echo";

    private static final long CLIENT_REQUEST_TIMEOUT_IN_SECONDS = 10L;

    private ClientAndServer server;
    private NettyHttpClient httpClient;

    @Before
    public void setUp() {
        // A simple echo server
        server = ClientAndServer.startClientAndServer(SERVER_PORT);
        server.when(request().withPath(ECHO_PATH))
                .callback(request -> response().withBody(request.getBodyAsString()));
        httpClient = new NettyHttpClient();
    }

    @After
    public void tearDown() {
        server.stop();
    }

    @Test
    public void sendMultipleRequestsSingleThreaded() throws ExecutionException, InterruptedException, TimeoutException {
        // succeeds
        scheduleTasksAndWaitForResponses(1);
    }

    @Test
    public void sendMultipleRequestsMultiThreaded() throws ExecutionException, InterruptedException, TimeoutException {
        // fails
        scheduleTasksAndWaitForResponses(3);
    }

    private void scheduleTasksAndWaitForResponses(int parallelThreads) throws InterruptedException, ExecutionException, TimeoutException {
        ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(parallelThreads);

        ScheduledFuture<?> schedule1 = executor.schedule(this::sendRequestAndVerifyResponse, 2L, TimeUnit.SECONDS);
        ScheduledFuture<?> schedule2 = executor.schedule(this::sendRequestAndVerifyResponse, 2L, TimeUnit.SECONDS);
        ScheduledFuture<?> schedule3 = executor.schedule(this::sendRequestAndVerifyResponse, 2L, TimeUnit.SECONDS);
        ScheduledFuture<?> schedule4 = executor.schedule(this::sendRequestAndVerifyResponse, 2L, TimeUnit.SECONDS);

        schedule1.get(CLIENT_REQUEST_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS);
        schedule2.get(CLIENT_REQUEST_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS);
        schedule3.get(CLIENT_REQUEST_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS);
        schedule4.get(CLIENT_REQUEST_TIMEOUT_IN_SECONDS, TimeUnit.SECONDS);
    }

    private void sendRequestAndVerifyResponse() {
        String requestBody = "thread: " + Thread.currentThread().getName() + ", random content: " + Math.random();
        HttpResponse httpResponse = httpClient.sendRequest(request().withMethod("POST").withPath(ECHO_PATH).withBody(requestBody), SERVER_ADDRESS);
        String responseBody = httpResponse.getBodyAsString();
        System.err.println("Sent request: " + requestBody + ". Received echo response: " + responseBody);
        Assert.assertEquals(requestBody, responseBody);
    }

}
`

**Comment by jamesdbloom** [comment] 2018-02-07 17:26
I can see the issue, essentially it is caused by requests crossing over on the web socket. I should be able to resolve this.

**Comment by jamesdbloom** [comment] 2018-02-09 08:33
Thanks for the test it was helpful to detect and resolve this issue.  I have added two very similar (Java 1.7) versions into the build.

This is now fixed and is available in the SNAPSHOT version.  I will make  new release soon, once I finished a few more items.

**Closed by jamesdbloom** 2018-02-09 08:33 UTC

**Comment by yaliev15** [comment] 2018-04-05 12:15
@jamesdbloom sorry for dummy question, but how can i get this SNAPSHOT version? Is it 5.3.1-SHAPSHOT or smt. ?
