### ISSUE TITLE
CORS * not accepted by my app

### ISSUE THREAD

**Issue by jameslive** [jamesdbloom/mockserver#468] opened 2018-05-06 00:16 UTC
Thank you for helping with questions around CORs previously.  I have come back to use the docker version of mockserver for another project, but this time when I enable CORS in my docker-compose.yml, the application does not accept '*' as a value when getting a response back from the mockserver.  I need a way to set the CORS value in the expectation to something like "http://localhost:8080" instead.  Is there a way to do this?  I tried to set the expectation this way, but it doesn't seem to work and just returns * for CORS.

Thanks for any advice.

I can layout more specific details if it is unclear.

**Comment by jamesdbloom** [comment] 2019-11-16 13:38
Closing as a duplicate of #441

**Closed by jamesdbloom** 2019-11-16 13:38 UTC

**Comment by jamesdbloom** [comment] 2019-11-16 13:39
I have closed this as a duplicate of #441 however I will shortly add the ability to override the defaults for all CORS header.
