### ISSUE TITLE
NoClassDefFoundError JcaPEMWriter

### ISSUE THREAD

**Issue by jontodd** [jamesdbloom/mockserver#122] opened 2015-04-22 21:44 UTC
I'm getting a NoClassDefFoundError for the JcaPEMWriter class within bouncy castle when trying to use the proxy for SSL connections.

Here's a snippet of the code:
```java
public class TestClass {
    {
        Security.addProvider(new BouncyCastleProvider());
    }
    
    private ClientAndProxy proxy;
    private ClientAndServer mockServer;

    @BeforeMethod
    public void setUp() throws Exception {
        mockServer = startClientAndServer(1080);
        proxy = startClientAndProxy(1090);
        proxy.dumpToLogAsJava();

    }

    @AfterMethod
    public void tearDown() throws Exception {
        proxy.stop();
        mockServer.stop();
    }

    @Test
    public void test() throws Exception {
        HttpClient httpClient = HttpClientBuilder.create()
                .setProxy(new HttpHost("localhost", 1090, "http"))
                .build();

        HttpResponse response = httpClient.execute(new HttpHost("google.com", 443, "https"), new HttpGet("/"));
        Assert.assertThat(response.getStatusLine().getStatusCode(), is(200));
    }
}
```

Stack Trace:
```
java.lang.NoClassDefFoundError: org/bouncycastle/openssl/jcajce/JcaPEMWriter
        at org.mockserver.socket.SSLFactory.dynamicallyCreateKeyStore(SSLFactory.java:171) ~[mockserver-core-3.9.9.jar:na]
        at org.mockserver.socket.SSLFactory.buildKeyStore(SSLFactory.java:155) ~[mockserver-core-3.9.9.jar:na]
        at org.mockserver.socket.SSLFactory.sslContext(SSLFactory.java:83) ~[mockserver-core-3.9.9.jar:na]
        at org.mockserver.socket.SSLFactory.createClientSSLEngine(SSLFactory.java:68) ~[mockserver-core-3.9.9.jar:na]
        at org.mockserver.proxy.relay.RelayConnectHandler$1$1.operationComplete(RelayConnectHandler.java:46) ~[mockserver-netty-3.9.9.jar:3.9.9]
        at org.mockserver.proxy.relay.RelayConnectHandler$1$1.operationComplete(RelayConnectHandler.java:37) ~[mockserver-netty-3.9.9.jar:3.9.9]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680) [netty-common-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:621) [netty-common-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138) [netty-common-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at org.mockserver.proxy.relay.RelayConnectHandler$1.channelActive(RelayConnectHandler.java:35) [mockserver-netty-3.9.9.jar:3.9.9]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:212) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:198) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:818) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:252) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:282) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.26.Final.jar:4.0.26.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.26.Final.jar:4.0.26.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.openssl.jcajce.JcaPEMWriter
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_76]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_76]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_76]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_76]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_76]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_76]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_76]
        ... 24 common frames omitted
```

I'm bringing in mock server via maven with: 

```xml
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>3.9.9</version>
            <scope>test</scope>
        </dependency>
```
Digging into the maven dependency:tree it looks like mock-server only has a transitive dependency on bcpkix-jdk15on which is the module which contains JcaPEMWriter which it acquires from depending on bcmail-jdkon. 
```
...
[INFO] |  +- org.mock-server:mockserver-client-java:jar:3.9.9:test
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.3.2:test
[INFO] |  +- org.mock-server:mockserver-core:jar:3.9.9:test
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:3.0.1:test
[INFO] |  |  +- io.netty:netty-codec-socks:jar:4.0.26.Final:test
[INFO] |  |  +- com.jcraft:jzlib:jar:1.1.2:test
[INFO] |  |  +- org.bouncycastle:bcmail-jdk15on:jar:1.51:test
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.50:test
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.5.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.2:compile
[INFO] |  |  +- org.skyscreamer:jsonassert:jar:1.2.3:test
[INFO] |  |  |  \- org.json:json:jar:20090211:test
[INFO] |  |  +- com.github.fge:json-schema-validator:jar:2.1.6:test
[INFO] |  |  |  +- com.github.fge:json-schema-core:jar:1.1.7:test
[INFO] |  |  |  |  +- com.github.fge:jackson-coreutils:jar:1.1:test
[INFO] |  |  |  |  +- org.mozilla:rhino:jar:1.7R4:test
[INFO] |  |  |  |  +- com.github.fge:uri-template:jar:0.5:test
[INFO] |  |  |  |  +- com.github.fge:msg-simple:jar:0.5:test
[INFO] |  |  |  |  \- com.github.fge:btf:jar:1.0:test
[INFO] |  |  |  +- javax.mail:mailapi:jar:1.4.3:test
[INFO] |  |  |  \- com.googlecode.libphonenumber:libphonenumber:jar:5.1:test
[INFO] |  |  \- commons-io:commons-io:jar:2.4:test
[INFO] |  +- io.netty:netty-buffer:jar:4.0.26.Final:test
[INFO] |  +- io.netty:netty-codec:jar:4.0.26.Final:test
[INFO] |  +- io.netty:netty-codec-http:jar:4.0.26.Final:test
[INFO] |  +- io.netty:netty-common:jar:4.0.26.Final:test
[INFO] |  +- io.netty:netty-handler:jar:4.0.26.Final:test
[INFO] |  +- io.netty:netty-transport:jar:4.0.26.Final:test
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.51:test
[INFO] |  +- janino:janino:jar:2.5.10:test
[INFO] |  \- junit:junit:jar:4.12:test
...
```

There are two issues with this:
1. The KeyStoreFactory class within mock server depends on JcaPEMWriter so the dependency should be made explicit in the project
2. For some reason maven pulls in the 1.50 version of bcpkix-jdk15on for the 1.51 version of bcmail-jdkon and the 1.50 version of bcpkix-jdk15on doesn't contain JcaPEMWriter.

I've tested locally that adding the following dependency to my project fixes the issue:

```xml
       <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.51</version>
        </dependency>
```

**Comment by jamesdbloom** [comment] 2015-04-23 05:41
I agree I'll add the dependency explicitly, however, thats strange because when I run dependency:tree I get the output below.  In addition when I run just your code in a new project I don't get the issue.

Either way I've added the dependency explicitly now.

```bash
[INFO] org.mock-server:mockserver-client-java:jar:3.9.10-SNAPSHOT
[INFO] +- org.mock-server:mockserver-core:jar:3.9.10-SNAPSHOT:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.0.1:compile
[INFO] |  +- io.netty:netty-buffer:jar:4.0.26.Final:compile
[INFO] |  |  \- io.netty:netty-common:jar:4.0.26.Final:compile
[INFO] |  +- io.netty:netty-codec:jar:4.0.26.Final:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.0.26.Final:compile
[INFO] |  +- io.netty:netty-codec-socks:jar:4.0.26.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.0.26.Final:compile
[INFO] |  +- io.netty:netty-transport:jar:4.0.26.Final:compile
[INFO] |  +- com.jcraft:jzlib:jar:1.1.2:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
[INFO] |  +- org.bouncycastle:bcmail-jdk15on:jar:1.51:compile
[INFO] |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.51:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.5.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.5.2:compile
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.2.3:compile
[INFO] |  |  \- org.json:json:jar:20090211:compile
[INFO] |  +- com.github.fge:json-schema-validator:jar:2.2.6:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.3:compile
[INFO] |  |  +- com.googlecode.libphonenumber:libphonenumber:jar:6.2:compile
[INFO] |  |  +- com.github.fge:json-schema-core:jar:1.2.5:compile
[INFO] |  |  |  +- com.github.fge:uri-template:jar:0.9:compile
[INFO] |  |  |  |  \- com.github.fge:msg-simple:jar:1.1:compile
[INFO] |  |  |  |     \- com.github.fge:btf:jar:1.2:compile
[INFO] |  |  |  +- com.github.fge:jackson-coreutils:jar:1.8:compile
[INFO] |  |  |  \- org.mozilla:rhino:jar:1.7R4:compile
[INFO] |  |  +- javax.mail:mailapi:jar:1.4.3:compile
[INFO] |  |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  |  \- net.sf.jopt-simple:jopt-simple:jar:4.6:compile
[INFO] |  \- commons-io:commons-io:jar:2.4:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] +- com.google.guava:guava:jar:18.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.10:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.2:runtime
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.2:runtime
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.mockito:mockito-all:jar:1.10.8:test
[INFO] \- org.hamcrest:hamcrest-all:jar:1.3:test
```

In addition just to make you aware you may get:

```java
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

If you haven't added the MockServer root CA to your JVM.  For an example of how to do this check out `mockserver/scripts/install_ca_certificate.sh`.  

you may also need to provide your JVM with the command line option:

```bash
-Djavax.net.ssl.trustStore=~/.keystore
```

I'm going to close this ticket as Its now fixed but re-open if the issue is still not resolved for you (on the latest SNAPSHOT).

**Closed by jamesdbloom** 2015-04-23 05:41 UTC

**Comment by jamesdbloom** [comment] 2015-04-24 05:35
Actually now with the latest commit you won't need to specify the `javax.net.ssl.trustStore` setting as I override this when you run the proxy directly in the JVM.  If a custom keystore is provided to the proxy then it will use this so the overriding of the default keystore is safe and still allows for users to provide their own keystore.
