### ISSUE TITLE
Simple HTTPS requests timeout using mockServer proxy

### ISSUE THREAD

**Issue by majiksniper** [jamesdbloom/mockserver#465] opened 2018-04-28 13:19 UTC
Java version is 1.8.0_161
OS: Mac Sierra
No system/default proxy

I start mockserver proxy using the following command
`java -jar mockserver-netty-5.3.0-jar-with-dependencies.jar -proxyPort 1090`

I now use postman to send requests using "127.0.0.1:1090" as proxy server.

When I make a normal HTTP request to an API, I get the response as expected and the proxy records it.
When I make a simple HTTPS GET request, the request times out and the debug info from the mockserver proxy running is:

```

WARN o.m.p.r.RelayConnectHandler Connection failed to 0.0.0.0/0.0.0.0:1090
io.netty.channel.ConnectTimeoutException: connection timed out: 0.0.0.0/0.0.0.0:1090
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) ~[mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [mockserver-netty-5.3.0-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

I am using a MAC, I haven't configured any system proxies, just raw internet. What could be the problem?

**Comment by vishaluk** [comment] 2018-04-29 21:31
I also do have the same problem. I tried accessing https://www.google.com from postman using mockserver as proxy and it will timeout. Using the same proxy but changing from https to http brings the correct response. Any update on this issue will be highly appreciated

**Comment by kh0ma** [comment] 2018-07-25 10:59
I have the same issue.

My steps:
Running windows 10 or linux (trying on both systems) through the cli:
`java -jar mockserver-netty-5.3.0-jar-with-dependencies.jar -proxyPort 9595`

Setup Postman to use the proxy on http and https.
Add or not (works same) certificate to system.

Then trying to get any http, works fine.

Then trying to get any https - fails.

Postman log:
```
GET
fb.com
01:40:40.757

Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://fb.com/
Proxy:
   host:"localhost"
   port:9595
   match:"http+https://*/*"
Request Headers:
   cache-control:"no-cache"
   postman-token:"5519d2f9-b963-4645-a02d-2c4cb38f6551"
```
LOGs from mockserver:
```
C:\Users\okhome\Desktop>java -jar mockserver-netty-5.3.0-jar-with-dependencies.jar -proxyPort 9595
2018-07-25 13:50:30,171 INFO o.m.p.http.HttpProxy MockServer started on port: 9595
2018-07-25 13:50:35,845 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:36,558 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "Ac7dNzyEYzScl7DOYHoE1Rku6PhV/Iao7/qePNw2mBQVsJhPvT6GqYFHBJL23K2GQOpjH5yMFrrGXjM9SxsDJg==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:36 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'Host: fb.com' -H 'accept-encoding: gzip, deflate' --compress -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:36,581 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "http://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:37,090 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "/62mqqAFN5subuq24aItSSirshUn1cF116xGiY37NSgFaVSwjeAtpSSoOuwDojWbv7gkRYgffW0HN0XRY85IgQ==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:36 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "http://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: http://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:37,092 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:37,562 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "BJvqAP32YV2biDO/SkhpEhdagcXwxBglqwKwxk5AOoZireCHuGixJ0afCHKTN39ByuumiyCIip/HvZmWl1o9pw==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:37 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:37,564 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:38,019 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "sIhFFQk5cvF9jIunziAMH8Sm16H9G1SHsvREEMcyqgl2YmAqSCsjM9o00an7OXdnPutgg/CF7Pj75BqS7YuLsA==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:37 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:38,020 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:38,480 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "vscskebZAs5ut4gqDXl9b5bwVAyrlUVC9jgVDQPZJtCYFvW/31PyVEhKkMHWQqjL8ha9qI3tCASYPhr5xuEzSQ==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:38 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:38,483 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:38,930 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "x2O4suZoVkkCFu4wSfUp3fVNB6j8QrNRisPb8kBuM1HCwOkrTNLDziXwaCgGserLSzXukHMyhnnAIMLXflS3QA==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:38 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:38,932 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:39,386 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "tOt/VB9nXEk4YxJjCC5BUZPCP3drOmIGZtGH2+07hRAY1QPY3y0DILWkdGeRabJOPcoVdlMbdiPWCSu8kjvtvQ==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:39 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:39,389 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:39,848 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "rdOB+JIlms5X2fmO7q9BTDnc4KyfzOx+A02KvuirjdOP0XJf4NWRyxpQDHiUSIO9W+f5fWEqf5Qjx6upNFgtDg==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:39 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:39,850 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:40,288 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "LpI5jZrA0f47EQB/BaTvuoDwL9IxVoI2cCvgImA+/lKOwvJpSe3bNnxG9VKQ1tFO095shhQbd2er5gQyAyJ5uA==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:40 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:40,290 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:40,764 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "unRE9Al4a7cA+PPJmK7DAbtFixxKg/cD4LMlS4gkpZ+GV/YywD7xaDJ6M2rwK/3gvJNwZS1WiqKyaiwMdeHMaA==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:40 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'

2018-07-25 13:50:40,769 INFO o.m.m.HttpStateHandler no active expectations when receiving request:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

2018-07-25 13:50:41,212 INFO o.m.m.HttpStateHandler returning response:

        {
          "statusCode" : 302,
          "reasonPhrase" : "Found",
          "headers" : {
            "Connection" : [ "keep-alive" ],
            "X-FB-Debug" : [ "qquPfoWCiQ83QcMVWtoZTTqOn2HGPcqGE9zOb5AcJx6QxWSAbc7yRXqnSpJKmJ9uo+1dmh58qT90/l/k3JYxkg==" ],
            "Content-Length" : [ "0" ],
            "Date" : [ "Wed, 25 Jul 2018 10:50:41 GMT" ],
            "Location" : [ "https://fb.com/" ],
            "Content-Type" : [ "text/html; charset=\"utf-8\"" ],
            "connection" : [ "keep-alive" ]
          }
        }

 for request as json:

        {
          "method" : "GET",
          "path" : "/",
          "headers" : {
            "referer" : [ "https://fb.com/" ],
            "content-length" : [ "0" ],
            "Accept" : [ "*/*" ],
            "User-Agent" : [ "PostmanRuntime/7.1.1" ],
            "Connection" : [ "keep-alive" ],
            "Postman-Token" : [ "db039c7d-fedb-4316-93cf-13510ffe4f28" ],
            "Host" : [ "fb.com" ],
            "cache-control" : [ "no-cache" ],
            "accept-encoding" : [ "gzip, deflate" ]
          },
          "keepAlive" : true,
          "secure" : false
        }

 as curl:

        curl -v 'http://fb.com/' -H 'cache-control: no-cache' -H 'Postman-Token: db039c7d-fedb-4316-93cf-13510ffe4f28' -H 'User-Agent: PostmanRuntime/7.1.1' -H 'Accept: */*' -H 'accept-encoding: gzip, deflate' --compress -H 'referer: https://fb.com/' -H 'Host: fb.com' -H 'Connection: keep-alive' -H 'content-length: 0'
```

**Comment by kh0ma** [comment] 2018-07-25 11:00
Notice that this log is clear for one request from postman.

**Comment by jamesdbloom** [comment] 2018-11-14 07:14
@kh0ma I can see from the log the original request was in HTTP and therefore you get the redirect to HTTP.  However postman resubmits the 302 redirect to HTTPS over the HTTP proxy.  This is a bug in postman because sending an HTTPS request over an HTTP proxy is invalid.  Only HTTP requests should be sent over an HTTP proxy.  I have confirmed that calling https://fb.com/ in chrome works correctly and gets redirected to https://www.facebook.com/ then Chrome correctly follows that request.  The same is the case when using Curl.  I'm closing this issue as the bug is with Postman incorrectly sending HTTPS requests over an HTTP proxy, instead Postman should be using HTTP CONNECT to send an HTTPS request over a proxy correctly.

@vishaluk your issue is completely separate, when you use an HTTP proxy the browser does not send the request to google via the proxy.  When you use an HTTPS proxy to google the browser (I assume like Chrome) does not allow the request because Chrome has certificate pinning for the TLS certificates corresponding to google.  When MockServer is used as an HTTPS proxy it has to generate a dynamic TLS certificate for google, but Chrome detects this is not the official google certificate it is expecting and so doesn't allow the request.  You can confirm this behaviour by using curl as follows and see the response from google:
```bash
curl -v -k https://localhost:1080/ -H "Host: www.google.com"
```

**Closed by jamesdbloom** 2018-11-14 07:14 UTC
