### ISSUE TITLE
How to clear XPath body expectations

### ISSUE THREAD

**Issue by ninckblokje** [jamesdbloom/mockserver#183] opened 2015-09-22 19:26 UTC
Hi,

We are upgrading from an older version of Mock Server (3.6.2) to a more recent one (3.9.17) and I have noticed a difference regarding clearing expectations.

We set an expectation for a POST request on a certain URL with an XPath body (unlimited times). The expectation is matched and I can retrieve the results. However clearing the expectations does not appear to work. When I add "not":"true" to my clear JSON request the expectations will get removed. Why is that and why don't I need to add "not":"true" to my other JSON requests?

Jeroen

**Comment by jamesdbloom** [comment] 2015-09-22 20:33
Can you please provide the exact expectations you are setting and then trying to clear so I can understand fully the issue you are having.

**Comment by ninckblokje** [comment] 2015-09-23 11:08
Hi,

Here are my JSON requests:

**Comment by ninckblokje** [comment] 2015-09-23 11:08
Expectation:
{
    "httpRequest": {
        "method": "POST",
        "path": "/SomeService",
        "body": {
            "type": "XPATH",
            "value": "(* and /*[local-name()='Envelope']/*[local-name()='Header']/*[local-name()='Context']/Id[text()='ValueX'])"
        },
        "headers": [
            {
                "name": "Content-Type",
                "values": [".*action=\"?.*search\"?.*"]
            }
        ]        
    },
    "httpResponse": {
        "statusCode": "200",
        "headers": [
            {
                "name": "Content-Type",
                "values": ["application/soap+xml; charset=utf-8"]
            }
        ],
        "body": "<SomeSoapEnvelope/>"
    },
    "times": {
        "unlimited": true
    },
    "timeToLive": {
        "timeUnit": "SECONDS",
        "timeToLive": 120,
        "unlimited": false
    }
}

**Comment by ninckblokje** [comment] 2015-09-23 11:09
Not working clear:
{
        "method": "POST",
        "path": "/SomeService",
        "body": {
            "type": "XPATH",
            "value": "(* and /*[local-name()='Envelope']/*[local-name()='Header']/*[local-name()='Context']/Id[text()='ValueX'])"
        },
        "headers": [
            {
                "name": "Content-Type",
                "values": [".*action=\"?.*search\"?.*"]
            }
        ]        
}

**Comment by ninckblokje** [comment] 2015-09-23 11:09
Working clear:
{
        "method": "POST",
        "path": "/SomeService",
        "body": {
            "type": "XPATH",
            "value": "(* and /*[local-name()='Envelope']/*[local-name()='Header']/*[local-name()='Context']/Id[text()='ValueX'])",
            "not":"true"
        },
        "headers": [
            {
                "name": "Content-Type",
                "values": [".*action=\"?.*search\"?.*"]
            }
        ]        
}

**Comment by jamesdbloom** [comment] 2015-09-25 05:21
I have identified the issue and written a fix, however I have not managed to write full test coverage for this and 100% finish of the code.  I'll do this in the next couple of days.

The root cause is that the matcher used in the call to `clear` ends up matching the `body` of the request matcher in the `clear` call against the original XPath expression, i.e.:

```json
{
    "type": "XPATH", 
    "value": "(* and /[local-name()='Envelope']/[local-name()='Header']/[local-name()='Context']/Id[text()='ValueX'])"
}
```

against

```xpath
(* and /[local-name()='Envelope']/[local-name()='Header']/[local-name()='Context']/Id[text()='ValueX'])
```

This means they do not match.  I have now written code to fix this issue which affect other types of complex bodies as well.  My fix will fix all types complex body matching for `clear` or other related operations that do this type of matching.

**Comment by jamesdbloom** [comment] 2015-09-25 05:23
p.s. I wrapped you blocks of json inside markdown json markers this make github format them in a nice way as it support markdown syntax inside issues

**Comment by jamesdbloom** [comment] 2015-09-25 12:41
this is now fixed but still needs some extra integration tests to ensure the full flow is covered

**Comment by ninckblokje** [comment] 2015-09-25 15:43
Thanks!
Once you are done I might try to backport it to 3.9.17 or 3.9.18.

**Comment by jamesdbloom** [comment] 2015-09-25 15:52
Is there a reason why you can't upgrade?  Most versions are pretty much backwards compatible as far as I'm aware.

**Comment by ninckblokje** [comment] 2015-09-25 15:56
Is there a newer version then 3.9.17?

We have a central MockServer for a lot of teams (our technology stack is limiting the possibilities). Not being able to clear the expectations can cause some problems with our tests.

The current version we are using (3.6.2) is having some performance problems. It tends to be slow, and it becomes more slower over time. Also we require a lot of 'default' expectations. We can solve this with a newer version (URL matches).

**Comment by jamesdbloom** [comment] 2015-09-25 16:35
The current version is 3.10.0, this was released last week but it won't have the fix I just made in it for your bug.  I suspect I'll realise that fix early next week.

3.10.0 does have a lot of improvements though so I would suggest upgrading.

I'm very interested you mention performance issues.  I would like to understand that more.  Perhaps I'll add an `info` endpoint that can return key metrics about what is currently happening in MockServer, if I do this I assume you could send me the results from the endpoint if the MockServer is performing slowly.  This should tell me if anything is going on inside to make it perform slowly and tune it.

**Comment by ninckblokje** [comment] 2015-09-25 18:52
I will have a look at the new version.

Some performance metric would be great! It would also help us diagnose the problem. Is there a max number of expectations we can set?

**Comment by jamesdbloom** [comment] 2015-09-26 22:18
I have now added the missing integration tests so I'm closing this ticket

**Closed by jamesdbloom** 2015-09-26 22:18 UTC
