### ISSUE TITLE
Unable to run multiple instances in JVM

### ISSUE THREAD

**Issue by viveksnv** [jamesdbloom/mockserver#266] opened 2016-07-23 17:27 UTC
I use gradle to run the tests and each test will start/stop the server and manage exceptions.

Gradle runs the tests parallel so if more than one test try to start/stop mock server, it does not work properly.

**Comment by jamesdbloom** [comment] 2017-06-21 16:40
This does work as long as you use a separate port for each instance, there are unit tests that do exactly this in the MockServer build.  It is not possible to bind multiple processes to the same port, which is an operating system / networking constraint.

I am closing this issue, if you have more evidence for what the problem is or can explain how to reproduce it please re-open this issue.

**Closed by jamesdbloom** 2017-06-21 16:40 UTC
