### ISSUE TITLE
Mockserver double-logging requests from 5.7.1

### ISSUE THREAD

**Issue by paprikati** [jamesdbloom/mockserver#685] opened 2019-11-11 13:15 UTC
In version `5.7.1`, we are seeing mockserver double logging a request:

In one specific test:
- We make 5 requests
- We call `retrieve`
- We consistently get back 6
- There is one specific request which is always there twice

This doesn't happen on `5.7.0`.

The truth is, we don't really know enough about mockserver to debug it more than that, but happy to work with you to try and form a repro case we can share.

This is what we get from mockserver (we've removed the headers, if you need them for repro we can send them to you but ideally not over github)
You can see 3 and 4 are the same, but we are definitely not retrying from our side.

```
Array
(
    [0] => stdClass Object
        (
            [method] => GET
            [path] => /xero/api.xro/2.0/Invoices
            [queryStringParameters] => stdClass Object
                (
                    [IDs] => Array
                        (
                            [0] => INV_GUID1_1,INV_GUID1_2,INV_GUID1_FLAKY_404,INV_GUID2_FLAKY_404,INV_GUID1_REALLY_NOT_FOUND
                        )
                )
        )
    [1] => stdClass Object
        (
            [method] => GET
            [path] => /xero/api.xro/2.0/Invoices/INV_GUID1_FLAKY_404
        )

    [2] => stdClass Object
        (
            [method] => GET
            [path] => /xero/api.xro/2.0/Invoices/INV_GUID2_FLAKY_404
        )

    [3] => stdClass Object
        (
            [method] => GET
            [path] => /xero/api.xro/2.0/Invoices/INV_GUID1_REALLY_NOT_FOUND
        )

    [4] => stdClass Object
        (
            [method] => GET
            [path] => /xero/api.xro/2.0/Invoices/INV_GUID1_REALLY_NOT_FOUND
          
        )

    [5] => stdClass Object
        (
            [method] => GET
            [path] => /xero/api.xro/2.0/Contacts/CON_GUID1_99
        )
)
```

**Comment by jamesdbloom** [comment] 2019-11-11 20:33
To reproduce this I need a little more logging or enough of you code to reproduce, I'm not interested in the header values but the rest of the logging is important because without this it is very difficult to reproduce or understand if there is an issue.

**Comment by paprikati** [comment] 2019-11-11 20:36
We have mockserver running in a docker container using your image. Are there specific logs I can get from that container which will help you?

**Comment by jamesdbloom** [comment] 2019-11-11 21:40
Ideally standard out from the container,  by running it without the `-d` flag or by using the `docker logs` command.  Please sanitize any sensitive values.

**Comment by paprikati** [comment] 2019-11-11 21:44
Cool will get that for you tomorrow morning

**Comment by jamesdbloom** [comment] 2019-11-11 21:45
thanks

**Comment by will-in-wi** [comment] 2019-11-15 22:09
We saw this too on this project: https://github.com/DripEmail/magento-m1-extension

The tests always have at least one double mock. We are hard-coding it to version 5.7.0 for now.

**Comment by jamesdbloom** [comment] 2019-11-16 07:58
@will-in-wi I can't reproduce this, can you please provide some example code to reproduce this or logs from when this has occured.

**Comment by jamesdbloom** [comment] 2019-11-16 08:35
I've reviewed all the code for this and I can't see where any duplication could be happening,  I made one change to improve something although I doubt this will have any impact.  Unless I can get some example code or logs to understand where / if there is an issue I won't be able to fix this.

**Comment by will-in-wi** [comment] 2019-11-16 13:32
I'm working on building a reproduction, but I noticed something about the headers which might be interesting. It looks like it might be related to keep-alive connections. Here's an example pair of requests:

```json
[{
  "method" : "POST",
  "path" : "/v2/123456/subscribers",
  "headers" : {
    "Host" : [ "mock:1080" ],
    "Connection" : [ "close" ],
    "Accept-encoding" : [ "gzip, deflate" ],
    "User-Agent" : [ "Drip Connect M1" ],
    "Authorization" : [ "Basic YWJjMTIzOg==" ],
    "Accept" : [ "application/json" ],
    "Content-Type" : [ "application/json" ],
    "X-Drip-Connect-Request-Id" : [ "5dcff8b140328" ],
    "Content-Length" : [ "22" ]
  },
  "keepAlive" : false,
  "secure" : false,
  "body" : {
    "type" : "STRING",
    "string" : "{\"subscribers\":[null]}",
    "contentType" : "application/json"
  }
}, {
  "method" : "POST",
  "path" : "/v2/123456/subscribers",
  "headers" : {
    "User-Agent" : [ "Drip Connect M1" ],
    "Authorization" : [ "Basic YWJjMTIzOg==" ],
    "Accept" : [ "application/json" ],
    "Content-Type" : [ "application/json" ],
    "X-Drip-Connect-Request-Id" : [ "5dcff8b140328" ],
    "x-forwarded-by" : [ "MockServer_62ae6ed4-6f65-4429-9859-a60f90237234" ],
    "host" : [ "mock:1080" ],
    "accept-encoding" : [ "gzip,deflate" ],
    "content-length" : [ "22" ],
    "connection" : [ "keep-alive" ]
  },
  "keepAlive" : true,
  "secure" : false,
  "body" : {
    "type" : "STRING",
    "string" : "{\"subscribers\":[null]}",
    "contentType" : "application/json"
  }
}]
```

**Comment by will-in-wi** [comment] 2019-11-16 14:08
It seems kind of like I have to use Docker Compose to successfully reproduce… But I have a minimal reproduction.

If you create the following as `docker-compose.yml` (Mine uses a different filename and the `-f` param, but it shouldn't matter):

```yaml
version: '3.7'
services:
  mock:
    image: jamesdbloom/mockserver:mockserver-5.7.1
    ports:
    - 1080:1080
```

And then run it with `docker-compose up`.

Then in another terminal, run:

```
curl -v -H "Host: mock:1080" "http://localhost:1080/blah"
```

It seems like the host header has a lot to do with it. If I remove that, there isn't an issue. In my case, the log output is:
```
$ docker-compose -f docker-compose-mocking.yml up
Creating network "devtools_m1_default" with the default driver
Creating devtools_m1_mock_1 ... done
Attaching to devtools_m1_mock_1
mock_1  |
mock_1  | java  -Dfile.encoding=UTF-8 -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar  -serverPort 1080 -logLevel INFO &
mock_1  |
mock_1  | 2019-11-16 14:06:41  org.mockserver.log.MockServerEventLog  INFO  started on port: 1080
mock_1  | 2019-11-16 14:06:44  org.mockserver.log.MockServerEventLog  INFO  received request:
mock_1  |
mock_1  | 	{
mock_1  | 	  "method" : "GET",
mock_1  | 	  "path" : "/blah",
mock_1  | 	  "headers" : {
mock_1  | 	    "Host" : [ "mock:1080" ],
mock_1  | 	    "User-Agent" : [ "curl/7.64.1" ],
mock_1  | 	    "Accept" : [ "*/*" ],
mock_1  | 	    "content-length" : [ "0" ]
mock_1  | 	  },
mock_1  | 	  "keepAlive" : true,
mock_1  | 	  "secure" : false
mock_1  | 	}
mock_1  |
mock_1  | 2019-11-16 14:06:44  org.mockserver.log.MockServerEventLog  INFO  received request:
mock_1  |
mock_1  | 	{
mock_1  | 	  "method" : "GET",
mock_1  | 	  "path" : "/blah",
mock_1  | 	  "headers" : {
mock_1  | 	    "User-Agent" : [ "curl/7.64.1" ],
mock_1  | 	    "Accept" : [ "*/*" ],
mock_1  | 	    "x-forwarded-by" : [ "MockServer_beb13a4b-fd6f-46e5-b8bc-b81c20d6342e" ],
mock_1  | 	    "host" : [ "mock:1080" ],
mock_1  | 	    "accept-encoding" : [ "gzip,deflate" ],
mock_1  | 	    "content-length" : [ "0" ],
mock_1  | 	    "connection" : [ "keep-alive" ]
mock_1  | 	  },
mock_1  | 	  "keepAlive" : true,
mock_1  | 	  "secure" : false
mock_1  | 	}
mock_1  |
mock_1  | 2019-11-16 14:06:44  org.mockserver.log.MockServerEventLog  INFO  no expectation for:
mock_1  |
mock_1  | 	{
mock_1  | 	  "method" : "GET",
mock_1  | 	  "path" : "/blah",
mock_1  | 	  "headers" : {
mock_1  | 	    "Host" : [ "mock:1080" ],
mock_1  | 	    "User-Agent" : [ "curl/7.64.1" ],
mock_1  | 	    "Accept" : [ "*/*" ],
mock_1  | 	    "content-length" : [ "0" ]
mock_1  | 	  },
mock_1  | 	  "keepAlive" : true,
mock_1  | 	  "secure" : false
mock_1  | 	}
mock_1  |
mock_1  |  returning response:
mock_1  |
mock_1  | 	{
mock_1  | 	  "statusCode" : 404,
mock_1  | 	  "reasonPhrase" : "Not Found",
mock_1  | 	  "headers" : {
mock_1  | 	    "x-forwarded-by" : [ "MockServer_beb13a4b-fd6f-46e5-b8bc-b81c20d6342e" ]
mock_1  | 	  }
mock_1  | 	}
mock_1  |
```

And the response from the API is:
```
$ curl -v -X PUT "http://localhost:1080/mockserver/retrieve?type=REQUESTS"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 1080 (#0)
> PUT /mockserver/retrieve?type=REQUESTS HTTP/1.1
> Host: localhost:1080
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< version: 5.7.1
< connection: keep-alive
< content-type: application/json; charset=utf-8
< content-length: 625
<
[ {
  "method" : "GET",
  "path" : "/blah",
  "headers" : {
    "Host" : [ "mock:1080" ],
    "User-Agent" : [ "curl/7.64.1" ],
    "Accept" : [ "*/*" ],
    "content-length" : [ "0" ]
  },
  "keepAlive" : true,
  "secure" : false
}, {
  "method" : "GET",
  "path" : "/blah",
  "headers" : {
    "User-Agent" : [ "curl/7.64.1" ],
    "Accept" : [ "*/*" ],
    "x-forwarded-by" : [ "MockServer_beb13a4b-fd6f-46e5-b8bc-b81c20d6342e" ],
    "host" : [ "mock:1080" ],
    "accept-encoding" : [ "gzip,deflate" ],
    "content-length" : [ "0" ],
    "connection" : [ "keep-alive" ]
  },
  "keepAlive" : true,
  "secure" : false
* Connection #0 to host localhost left intact
} ]* Closing connection 0
```

It kind of looks like it might be related to docker compose networking… If I run `docker run -p 1080:1080 jamesdbloom/mockserver:mockserver-5.7.1` it behaves correctly.

This one is really weird…

**Comment by jamesdbloom** [comment] 2019-11-16 20:08
@will-in-wi great I'll use that to try to reproduce on my side so I can debug it and fix it.  It'll be fixed in the next release in the next few days (possibly even today).

**Comment by will-in-wi** [comment] 2019-11-16 20:18
Splendid! Thanks for working on this, and thanks for the software! I ran across it when I was considering writing my own version of this for an issue I was facing, and mockserver fit the bill perfectly.

Please let me know if my instructions don't work for you, I can dig in further.

**Comment by jamesdbloom** [comment] 2019-11-16 20:50
Actually I can see what the problem is, I just need to think about the best way to solve the issue.  It looks like it only occurs when there are no matched expectations and the IP address of the MockServer doesn't match the Host header, such as when there is a load balancer or bridge (i.e. docker bridge) in front of the MockServer.

**Comment by jamesdbloom** [comment] 2019-11-16 23:08
This is now fixed and I am currently doing a release of a new version 5.7.2, although it'll take a few hours to appear in Maven Central.

**Closed by jamesdbloom** 2019-11-16 23:08 UTC
Labels: bug, need_more_information

**Comment by will-in-wi** [comment] 2019-11-17 19:20
Thank you so much!

**Comment by paprikati** [comment] 2019-11-18 11:13
Apologies I didnt get back to you - got caught up with other things.
This has also fixed our issue too - thanks so much!
