### ISSUE TITLE
transfer-encoding chunked not working properly

### ISSUE THREAD

**Issue by shollander** [jamesdbloom/mockserver#269] opened 2016-07-28 17:38 UTC
I have a client that sends a chunked request. It does not set the `Content-Length` header and sets `Transfer-Encoding: chunked`. When verifying the request using mock server, I see a `Content-Length` header and no `Transfer-Encoding: chunked`. 

I used `tcpdump -i lo` to inspect the raw packets and verified that my client is sending the HTTP request as I expect. For some reason MockServer is transforming the request to something else.

**Comment by jamesdbloom** [comment] 2017-11-16 21:01
It would be helpful if you could provide a code example.  I'll try to look into this either way, but it would probably a little faster if you could provide some example code.

**Comment by jamesdbloom** [comment] 2019-11-22 16:53
closing issue due to not enough information to resolve

**Closed by jamesdbloom** 2019-11-22 16:53 UTC
Labels: bug, need_more_information

**Comment by OscarNeira** [comment] 2020-02-06 08:19
Hi, I have the same issue. My client sending chunk data and somehow mockserver does not set  and response with the correct headers.

here is the log from the mockserver:
```for request:

	{
	  "method" : "POST",
	  "path" : "/api/1/space/spectrum-aa-1/objects/jesus-test-21722%2Ftest_createSingleSmallCall%2Fload-test-1/payload",
	  "headers" : {
	    "x-spectrum-access-token" : [ "" ],
	    "Content-Type" : [ "application/octet-stream" ],
	    "x-spectrum-meta-fs2_headers_test-name" : [ "[\"test_createSingleSmallCall\"]" ],
	    "x-spectrum-meta-fs2_metadata_dataDefinitionId" : [ "Payload" ],
	    "x-spectrum-meta-wasZippedFirst" : [ "false" ],
	    "x-spectrum-meta-fs2_headers_metadata" : [ "[{\"metadata\":{\"INT_TAGS\":[],\"INT_DOC_SLA\":[\"NONE\"],\"INT_COMP_LEVEL\":[\"PCI DSS\"]}}]" ],
	    "x-spectrum-meta-fs2_metadata_createdBy" : [ "FS2" ],
	    "x-spectrum-meta-fs2_headers_test-header" : [ "[\"test-header-value\"]" ],
	    "source" : [ "G2_SB_DEV_INT" ],
	    "ttl" : [ "50000" ],
	    "x-spectrum-meta-fs2_metadata_uri" : [ "fs2://spectrum@unit-test/jesus-test-21722/test_createSingleSmallCall/load-test-1" ],
	    "x-spectrum-meta-fs2_metadata_ttl" : [ "50000" ],
	    "x-spectrum-meta-fs2_metadata_createdOn" : [ "Thu Feb 06 09:56:31 EET 2020" ],
	    "timestamp" : [ "1580975791654" ],
	    "Connection" : [ "Keep-Alive" ],
	    "Accept-Encoding" : [ "gzip,deflate" ],
	    "User-Agent" : [ "Apache-HttpClient/4.5.11 (Java/11.0.2)" ],
	    "content-length" : [ "56" ]
	  },
	  "keepAlive" : true,
	  "secure" : false,
	  "body" : "T2pvNlZHaHBjMTlKYzE5RlkyOWtaV1JmWm5KdmJWOVBjMk5oY2w5MGIxOUtaWE4xY3pvNk9nPT0="
	}
````

This is the request from the client sending chunk data.

![Local-chunked-mock](https://user-images.githubusercontent.com/6389828/73917701-9ba28580-48c8-11ea-97e4-375eef7c12b9.png)

As you can see there is ```Transfer-Encoding: chunked``` 

Now Attached the tcpdump file from the incoming requests to mockserver: 

[tcpdump-nodeport-chunk.pcap.zip](https://github.com/mock-server/mockserver/files/4163869/tcpdump-nodeport-chunk.pcap.zip)
 
As you can see the mock server gets all headers from the client.

![pod-tcpdump-incoming](https://user-images.githubusercontent.com/6389828/73917845-ec19e300-48c8-11ea-9c1f-f28c9ec8af41.png)

**Comment by jamesdbloom** [comment] 2020-02-06 11:48
@OscarNeira I'm not sure what you mean by "mockserver does not set and response with the correct headers."  

Also, the pcap file you've attached doesn't contain any HTTP requests, instead, it contains SOCKS connection requests and encrypted TCP packets.

Is it possible to provide a code example that shows the problem you are having so I can reproduce it?

**Comment by OscarNeira** [comment] 2020-02-06 12:48
What I meant is why the mock server is changing the ```Transfer-Encoding: chunked``` header to ```content-length" : [ "56" ]``` as you can verify in the logs in mockserver.  

Sure I can give you an example:

1. Created new simple Java client here:

- Get the example here: https://github.com/OscarNeira/simple-java-client

2. Use a mock server to inspect the incoming request from the Nginx.

- You can use this version that includes the tcpdump layer in docker: https://github.com/OscarNeira/mockserver/tree/add/tcpdumps

3. Deployed the mock server in local Kubernetes cluster Minikube or MicroK8s

- Use the Java client to create expectations: Run the test in the project (CreateSimpleExpectation and CreateSimpleExpectationPost) remember to use the NodePort service.

- Test expectations with curl -v GET http://<CLUSTER-IP:NODEPORT>/delay/1

4. Use tcpdump in mockserver pod ```Kubectl exec –it <POD_NAME> -- /bin/bash```

- Once inside the pod run tcpdump -w tcpdump.pcap

- New terminal copy the file to local folder Kubectl cp <NAMESPACE>/ <POD_NAME>:tcpdump-ingress.pcap ~/tcpdump.pcap

5. To see the header information you can use Wireshark and right click ```Follow TCP Stream``` 

![Screenshot 2020-02-06 at 14 36 57](https://user-images.githubusercontent.com/6389828/73937948-e0d9ae00-48ee-11ea-8db9-f7b17af96fa7.png)

![pod-tcpdump-incoming](https://user-images.githubusercontent.com/6389828/73938132-5180ca80-48ef-11ea-9671-93e2cffe8242.png)

**Comment by jamesdbloom** [comment] 2020-02-06 13:54
MockServer is using Netty's `io.netty.handler.codec.http.HttpObjectAggregator` which aggregates chunks into a single request and swaps the `Transfer-Encoding: chunked` header for a `Content-Length` header. 

Other then the logs showing the wrong header is this causing any issues?

**Comment by OscarNeira** [comment] 2020-02-07 07:08
Thanks for the answer. Nop, there is no other issue atm. We want to use the mock server response to confirm that the client is sending the correct headers. In this case, we are going to skip the check for the Transfer-Encoding.

**Comment by LeiYangGH** [comment] 2023-08-18 06:12
i have same problem. our server responses as chunked. and we have client that relies each chunks size and then read it's bytes accordingly. but the response of mockserver is all body bytes, which totally breaks the client.

**Comment by andrake16** [comment] 2024-09-24 15:04
have this issue when using httpForward. Target server response headers
```
content-type: application/octet-stream; charset=UTF-8
transfer-encoding: chunked
```
in file there is xml and digital signature

but Mockserver after forwarding return response headers
```
connection: keep-alive
content-length: 4558
```
mockserver return different binary stream include xml part - some part of it equals but something is different when i see it in hex editor.
as a result after forwarding - returned file(i save response as bin file) contains wrong digital signature that can't be verified.

i don't know how to force mockserver return server's response as is - without changing headers and body data.
also somewhy server respond in CR ANSI but Mockserver forwarder change reponse to CR UTF-8
when i open reponse file in notepad++
this means that may be cause of issue is in encoding and line separator?

Mockserver 5.15.0
running in docker desctop on Windows 10

**Comment by andrake16** [comment] 2024-09-24 15:06
meanwhile when i used Fiddler classic to forwarding the same request - it return me correct data and signature verified correctly. Sorry for my English)
