### ISSUE TITLE
ConcurrentModificationException when creating expectations

### ISSUE THREAD

**Issue by khanh-nguyen** [jamesdbloom/mockserver#138] opened 2015-05-31 03:37 UTC
I have multiple tests running in parallel. Expectations are matched using cookies to avoid collisions. The mock server is `mockserver-netty-3.9.12`. To create expectations, I use `mockserver-client-node@1.0.5`. 
However, I get `ConcurrentModificationException` when creating expectations.
```
ERROR o.m.m.MockServerHandler Exception processing {
  "method" : "PUT",
  "path" : "/expectation",
  "headers" : [ {
    "name" : "Host",
    "values" : [ "localhost:9090" ]
  }, {
    "name" : "Connection",
    "values" : [ "close" ]
  }, {
    "name" : "Content-Length",
    "values" : [ "407" ]
  } ],
  "body" : "details omitted"
}
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[na:1.7.0_45]
	at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[na:1.7.0_45]
	at com.google.common.collect.Iterators.indexOf(Iterators.java:777) ~[mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at com.google.common.collect.Iterators.any(Iterators.java:684) ~[mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at com.google.common.collect.Iterables.any(Iterables.java:623) ~[mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at com.google.common.collect.Collections2$FilteredCollection.isEmpty(Collections2.java:186) ~[mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at org.mockserver.mock.MockServerMatcher.when(MockServerMatcher.java:43) ~[mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:69) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:34) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:88) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:39) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:20) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-3.9.12-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

**Comment by khanh-nguyen** [comment] 2015-05-31 03:43
I've just tried the latest version `mockserver-netty-3.9.15-jar-with-dependencies.jar` but got the same error.

**Comment by jamesdbloom** [comment] 2015-05-31 05:39
It is not possible with maven to change any already released code.  So the fix for this will only be in release 3.9.16.  I will do another release to create 3.9.16 in the next few days.  In the mean time if you want to have the fix sooner you can use the 3.9.16-SNAPSHOT version which is not yet released.  

To do that you need to configure your maven settings.xml or your pom.xml to include the Sonatype SNAPSHOT repository as follows: 

```xml
<profile>
    <id>sonatype</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>sonatype-nexus-snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>sonatype-nexus-snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</profile>
```

**Closed by jamesdbloom** 2015-05-31 05:39 UTC

**Comment by khanh-nguyen** [comment] 2015-05-31 16:44
:+1: Yes, that works. Thank you very much for your quick response.

**Comment by borhub** [comment] 2015-06-19 06:41
I've just hit this same issue. Is the 3.9.16 release with this fix coming any time soon? "Next few days" comment was 19 days ago ;) I'd prefer to wait for the actual release rather than use the snapshot. Thanks!

**Comment by jamesdbloom** [comment] 2015-06-19 08:20
Yes sorry I was hoping to squeeze another couple of minor fixes into the next release.  They are now completed so I can release this by end of the weekend.

**Comment by borhub** [comment] 2015-06-22 02:17
Thanks for the weekend release. I can confirm that with the latest Docker container it looks like I don't need to throttle the mocks' setup calls anymore. (I have run it 4 times without issues.)

**Comment by janonymus** [comment] 2015-06-23 08:52
Thank you for the release, i also had the same problem before and was watching this issue for a while, but since this release i don't get that error any more
