### ISSUE TITLE
Cannot configure the logging when using the maven plugin

### ISSUE THREAD

**Issue by alexcojocaru** [jamesdbloom/mockserver#133] opened 2015-05-21 20:00 UTC
I run the mock server (v 3.9.15) using the maven plugin:
```
<plugin>
						<groupId>org.mock-server</groupId>
						<artifactId>mockserver-maven-plugin</artifactId>
						<version>${dependency.mockserver.version}</version>
						<configuration>
							<serverPort>${cid.mock.svc.port}</serverPort>
							<proxyPort>${cid.mock.proxy.port}</proxyPort>
							<logLevel>WARN</logLevel>
							<initializationClass>....CidMockServerInitialization</initializationClass>
						</configuration>
						<executions>
							<execution>
								<id>maven-mockserver-plugin-run</id>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>start</goal>
								</goals>
							</execution>
							<execution>
								<id>maven-mockserver-plugin-stop</id>
								<phase>post-integration-test</phase>
								<goals>
									<goal>stop</goal>
								</goals>
							</execution>
						</executions>
```

The log level is set to WARN, and there is no custom logback file available in the classpath (there is a logback-test.xml though).
And still, the mock server uses the INFO level, and it does all the output to the console:
```
[INFO] creating expectation:
	{
	  "httpRequest" : {
	    "path" : "/api/directory/group(/.*)?",
	    "headers" : [ {
	      "name" : "X-FORWARD-ACCOUNTUUID",
	      "values" : [ "((?!aaaaaaaa\\-aaaa\\-4aaa\\-9aaa-)[0-9a-f\\-]{24})[0-9a-f\\-]{12}" ]
	    } ]
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpCallback" : {
	    "callbackClass" : "....GroupCallback"
	  },
	  "stillAlive" : true
	}
```

I even tried to set the log level using the JVM arg on the maven process:  -Dmockserver.logLevel=OFF or  -Dmockserver.logLevel=WARN, and the setting is still not applied.

**Comment by jamesdbloom** [comment] 2015-05-30 16:07
I can't reproduce this issue.

When I use the following configuration no log file is created:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-issue-133</artifactId>
    <version>1.0.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>3.9.15</version>
                <configuration>
                    <serverPort>1080</serverPort>
                    <proxyPort>1090</proxyPort>
                    <logLevel>WARN</logLevel>
                </configuration>
                <executions>
                    <execution>
                        <id>maven-mockserver-plugin-run</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>maven-mockserver-plugin-stop</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

However when I use the following configuration with a different logLevel setting a log file is created:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-issue-133</artifactId>
    <version>1.0.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>3.9.15</version>
                <configuration>
                    <serverPort>1080</serverPort>
                    <proxyPort>1090</proxyPort>
                    <logLevel>TRACE</logLevel>
                </configuration>
                <executions>
                    <execution>
                        <id>maven-mockserver-plugin-run</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>maven-mockserver-plugin-stop</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

I did however notice a separate minor bug with the `log.dir ` system property not being correctly defaulted.  I have fixed this issue.

I am going to close this issue as I can't reproduce it.  If you can provide more information or a full example that is not working I am very happy to re-open this issue.

**Comment by alexcojocaru** [comment] 2015-06-02 19:06
I created a basic maven project and set up the mockserver maven plugin with an initialization class. The logback config sets the root log level to WARN, and so does the logLevel property on the plugin configuration in the pom file.
Here's the link to the sample project: https://dl.dropboxusercontent.com/u/5995753/mockserver-logging.tar.gz. Run `mvn clean verify` in the project root folder and check out the output in the console.

**Comment by jamesdbloom** [comment] 2015-06-03 05:15
It looks like there is an issue for `start` and `stop` but I was testing with `runForked` and `stopForked`, I'm reopening this issue.

**Comment by jamesdbloom** [comment] 2015-06-03 05:58
It looks like the problem is that logback has a bug and once the logger is setup it is completely impossible to change the log level settings.  There are several methods to do this but all of them are complete ignored.  I try this a bit more but unfortunately it may just be impossible to do with logback until they fix their bug.  I'll also raise the bug with them.

**Comment by jamesdbloom** [comment] 2015-06-03 05:59
It you want to disable the logging in the mean time please use `runForked` and `stopForked` which should work identically (except that it forks a JVM in the background, then stops it again).

**Comment by alexcojocaru** [comment] 2015-06-03 06:36
Can you point me to the logback config which takes precedence and gets applied in the provided sample? I included a logback.xml under src/main/resources and a logback-test.xml under src/test/resources, hoping one of them would be picked up by logback, but they are both ignored, just as you mentioned earlier.

**Comment by jamesdbloom** [comment] 2015-06-03 07:56
Unfortunately because of the way maven works a simple solution like this is not possible.  The problem is that maven separates everything in separate classpath loaders, which is my opinion is a massive over complexity for very little benefit, however it makes it very hard to override classes for a plugin or used by a plugin.  For example to load the initialiser I explicitly have to import that classpath into the plugin classloader in code.

**Comment by jamesdbloom** [comment] 2015-06-03 08:22
Actually I also released there may be no way to override the logging level at Maven forces the plugin to use its logging libraries and it only uses SimpleLogger from an old version of SLF4J.  With this logger it is not possible to override the log level at all unless you provide a system property `org.slf4j.simpleLogger.defaultLogLevel` but this will affect all of the maven logging.  Which is the same as specifying the -q setting in maven.  Basically as I mentioned above maven has massively overcomplicated the classpath and dependency handling so unfortunately making elegant plugins is much harder then it should be.

**Comment by alexcojocaru** [comment] 2015-06-03 15:41
I arrived at the same conclusion after printing out the result of `LoggerFactory.getILoggerFactory().getClass()` in the custom mock server initialization class.
For now, I will look into using the `runForked` and `stopForked`.

**Comment by jamesdbloom** [comment] 2015-06-29 16:24
This is now fixed in the latest SNAPSHOT version and I'll also be doing a release very shortly.

**Closed by jamesdbloom** 2015-06-29 16:24 UTC
Labels: bug

**Comment by alexcojocaru** [comment] 2015-07-29 20:35
Thank you for fixing it. I have been using the new version for a while now and it works as expected.
