### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise

### ISSUE THREAD

**Issue by many086** [jamesdbloom/mockserver#272] opened 2016-08-04 03:00 UTC
the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1352)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1340)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1205)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)

Exception in thread "NettyClientWorkerThread_3" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [io.netty.util.concurrent.DefaultPromise$2]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1342)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1205)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
    ... 4 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.netty.util.concurrent.DefaultPromise$2]. The following stack trace is thrown for debugging purposes as well as 
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "NettyClientWorkerThread_4" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "NettyClientWorkerThread_1" Exception in thread "NettyClientWorkerThread_2" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "NettyClientSelector_1" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "NettyClientSelector_1" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590)
    at io

**Comment by many086** [comment] 2016-08-04 03:01
my application start error

**Comment by jamesdbloom** [comment] 2016-10-16 14:43
Can you provide some more detail about what you are doing and when you get this issue.  The MockServer war currently loads correctly inside Tomcat so I need to understand what you are doing differently or where the issue is.

**Comment by jamesdbloom** [comment] 2016-10-16 14:56
There are integration test in the build which test deploying both the MockServer war and MockServer Proxy was to tomcat.  I have also just manually tested this on a fresh install of Tomcat 8 and it worked correct without any class loading exceptions.  So I'll need more information about you specific setup to understand what is happening in your case.

**Comment by jamesdbloom** [comment] 2017-11-16 09:32
Closing as no longer considered an issue, if more background / logs, etc can be provided please re-open.

**Closed by jamesdbloom** 2017-11-16 09:32 UTC
Labels: question

**Comment by wangenxian** [comment] 2019-09-19 08:45
I've had this problem too, but I haven't solved it yet

**Comment by phpisfuture** [comment] 2020-11-30 14:21
> I've had this problem too, but I haven't solved it yet

me too
