### ISSUE TITLE
Matching Content-Type when it contains multiple values

### ISSUE THREAD

**Issue by nheitz** [jamesdbloom/mockserver#199] opened 2015-11-19 14:49 UTC
*Given the following expectation:*

      {
	  "httpRequest" : {
	    "method" : "PUT",
	    "path" : "/documents/doc-id",
	    "headers" : [ {
	      "name" : "Content-Type",
	      "values" : [ "application/x.audacity+txt", "application/x.tsv" ]
	    } ]
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 201,
	    "headers" : [ {
	      "name" : "Content-Type",
	      "values" : [ "application/json" ]
	    } ],
	    "body" : "{\n  \"artifactId\" : \"doc-id\",\n  \"artifactMd5Hex\" : \"doc-hex\"\n}"
	  }
	}

*I get the following response:*

      {
	  "method" : "PUT",
	  "path" : "/documents/doc-id",
	  "headers" : [ {
	    "name" : "Content-Type",
	    "values" : [ "application/x.audacity+txt" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "15" ]
	  }, {
	    "name" : "Host",
	    "values" : [ "localhost:34364" ]
	  }, {
	    "name" : "Connection",
	    "values" : [ "Keep-Alive" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "test" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false,
	  "body" : {
	    "type" : "BINARY",
	    "value" : "U29tZSBhdWRpbyBkYXRh"
	  }
	}

 did not match expectation:

	{
	  "method" : "PUT",
	  "path" : "/documents/doc-id",
	  "headers" : [ {
	    "name" : "Content-Type",
	    "values" : [ "application/x.audacity+txt", "application/x.tsv" ]
	  } ]
	}

 because:

	method matches = true
	path matches = true
	query string parameters match = true
	body matches = true
	headers match = false
	cookies match = true
	keep-alive matches = true
	ssl matches = true

This seems wrong to me.  Is it not the case that multiple values in the expectation of Content-Type (effectively Accept for the server) should be treated as a logical OR?  I'm expecting either  "application/x.audacity+txt" or  "application/x.tsv" to work.

**Comment by jamesdbloom** [comment] 2016-02-08 13:34
The problem is that it is not possible for MockServer to know if you want an OR or an AND.  In addition there is no specific logic to handle Content-Type separate from any other type of header for matching.  

There are two ways to get what you need with the existing MockServer logic:
1. Define a separate expectation for each different value of the Content-Type header.
2. Use a regex header value that matches both types of header value.

**Comment by nheitz** [comment] 2016-02-27 10:51
Thanks for your reply. I'm struggling to imagine a use case where one would want the accept header to act like an AND...but I'm willing to believe that that might be in the http spec somewhere. 

I think separate expectations actually makes the most sense, even though it imposes some redundancy. Thanks for the suggestion

**Comment by jamesdbloom** [comment] 2016-03-04 22:16
I am going to close this ticket, as it is not a bug.  If you need advice or feel there is missing logic please re-open.

**Closed by jamesdbloom** 2016-03-04 22:16 UTC
