### ISSUE TITLE
POST JSON with expectations with HTTP client of your choice

### ISSUE THREAD

**Issue by poohsen** [jamesdbloom/mockserver#296] opened 2016-11-09 17:10 UTC
hi,

in the past I have set up expectations using the Java client but for more ad hoc, lightweight testing I don't want to be compiling Java classes. So I thought I'd try JavaScript, but there, too it's not a matter of firing up node and typing in any JS. You need the mockserver-client module, and to install it you need a package.json. And all that even though it says in the docs that "To specify a request matcher in JavaScript use JSON". Why can't I just POST some JSON to the mock-server using e.g. cURL?

**Comment by jamesdbloom** [comment] 2016-11-09 19:40
You can't the clients are only provided to make things simpler.

I do plan on documenting the JSON Rest API to make this more straight forward, see #287.

I'm going to close this as a duplicate of #287.

**Closed by jamesdbloom** 2016-11-09 19:40 UTC

**Comment by poohsen** [comment] 2016-11-10 08:44
ah, nice! I dug around in the code a bit and found the /expectation endpoint. So it's just a PUT to `/expectation` with the JSON that can be copied from the JS examples but without JSON.stringify. The "body" value is a string that contains a serialized JSON object with quotation marks escaped like so:

{
       "httpRequest": {
           "method": "GET",
           "path": "/ts-json",
           "queryStringParameters": [
           ]
       },
       "httpResponse": {
           "statusCode": 200,
          "body": "{\"timestamp\": \"2010-01-01T00:00:00Z\""
      }
  }

cool, thanks!
