### ISSUE TITLE
Change sendExpectations method to public in mockserver client

### ISSUE THREAD

**Issue by jimkohl** [jamesdbloom/mockserver#424] opened 2018-01-29 13:42 UTC
James, moving this point here because it would be very useful to be able to invoke sendExpectation programmatically as I store all my json Expectations in files then want to send them over to ms after user selects from a plugin GUI that I'm working on.

You replied with reservations:
 The change to the sendException is more controversial and also has merge conflicts so I'm not sure it the right thing for now. This is intended as an internal function and has no validation, etc. This function is called by the ForwardChainExpectation as per the internal Mockito pattern. I'm open to discussing / understanding why you think exposing this is a good idea and implementing a solution but I'm not sure the answer is just to expose this method.

My thinking is that I just want a programmatic method (like sendExpectation).  It doesn't need to be sendExpectation :)

**Comment by jamesdbloom** [comment] 2018-01-29 17:10
Yes there is a plan to add some support related to this. Also may including scanning a file location or reading from S3, etc.

Once I get the next release out I can look at this.

**Comment by jamesdbloom** [comment] 2018-11-18 19:39
This is a duplicate of #503 so I'm going to close this issue.

**Closed by jamesdbloom** 2018-11-18 19:39 UTC
Labels: enhancement
