### ISSUE TITLE
mockserver_request.log file isn't created

### ISSUE THREAD

**Issue by TKolesnikova** [jamesdbloom/mockserver#254] opened 2016-06-10 14:48 UTC
I'm using MockServer Proxy for recording browser activity and can not figure out how to save recorded requests to the mockserver_request.log

I do the following: 

```
ClientAndProxy proxy = ClientAndProxy.startClientAndProxy(1090);
proxy.dumpToLogAsJSON();

// browse using browser with configured proxy on localhost:1090.

proxy.stop();

```

I see recorded requests in IDE console but the .log file doesn't appear anywhere.

**Comment by masooh** [comment] 2016-07-15 16:54
Struggled with the same issue. A logger with name REQUEST is necessary:

```xml
<!-- request log configuration -->
<appender name="REQUEST_LOG" class="org.mockserver.logging.DelayedFileCreationRollingFileAppender">
    <file>${log.dir:-./}mockserver_request.log</file>

    <encoder>
        <pattern>%msg%n</pattern>
    </encoder>

    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
        <fileNamePattern>${log.dir:-./}mockserver_request.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
        <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
            <maxFileSize>100MB</maxFileSize>
        </timeBasedFileNamingAndTriggeringPolicy>
        <maxHistory>3</maxHistory>
    </rollingPolicy>
</appender>

<logger name="REQUEST" level="INFO" additivity="false">
    <appender-ref ref="REQUEST_LOG"/>
</logger>
```

Snippet is from mockserver-examples.

**Comment by VitalyKheifets** [comment] 2017-01-23 13:19
I tryed the logback.xml above, but it is not working for me..

When i use the following logback.xml
https://github.com/jamesdbloom/mockserver/blob/master/mockserver-examples/src/main/resources/logback.xml
```
<configuration debug="false">
    <!-- To completely disable all logging completely -Droot.logLevel=OFF -Dmockserver.logLevel=OFF -->

    <!-- application log -->
    <appender name="FILE" class="org.mockserver.logging.DelayedFileCreationRollingFileAppender">
        <file>${log.dir:-./}mockserver.log</file>
        <encoder>
            <pattern>%date %level [%thread] %logger{35} [%file:%line] %msg%n</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>TRACE</level>
        </filter>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${log.dir:-./}mockserver.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>100MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
            <maxHistory>1</maxHistory>
        </rollingPolicy>
    </appender>

    <!-- make application log asynchronous -->
    <appender name="ASYNC_FILE" class="ch.qos.logback.classic.AsyncAppender">
        <queueSize>128</queueSize>
        <discardingThreshold>0</discardingThreshold>
        <appender-ref ref="FILE" />
    </appender>

    <!-- application console log (for errors and warnings) -->
    <appender name="STDERR" class="ch.qos.logback.core.ConsoleAppender">
        <target>System.err</target>
        <encoder>
            <pattern>%date %level %logger{20} %msg%n</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>WARN</level>
        </filter>
    </appender>

    <!-- make console log (for errors and warnings) asynchronous -->
    <appender name="ASYNC_STDERR" class="ch.qos.logback.classic.AsyncAppender">
        <queueSize>128</queueSize>
        <discardingThreshold>0</discardingThreshold>
        <appender-ref ref="STDERR" />
    </appender>

    <!-- application console log -->
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <target>System.out</target>
        <encoder>
            <pattern>%date %level %logger{20} %msg%n</pattern>
        </encoder>
        <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
            <evaluator>
                <expression>level &gt;= INFO &amp;&amp; level &lt; WARN</expression>
            </evaluator>
            <OnMismatch>DENY</OnMismatch>
            <OnMatch>NEUTRAL</OnMatch>
        </filter>
    </appender>

    <!-- make console log asynchronous -->
    <appender name="ASYNC_STDOUT" class="ch.qos.logback.classic.AsyncAppender">
        <queueSize>128</queueSize>
        <discardingThreshold>0</discardingThreshold>
        <appender-ref ref="STDOUT" />
    </appender>

    <!-- request log configuration -->
    <appender name="REQUEST_LOG" class="org.mockserver.logging.DelayedFileCreationRollingFileAppender">
        <file>${log.dir:-./}mockserver_request.log</file>

        <encoder>
            <pattern>%msg%n</pattern>
        </encoder>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${log.dir:-./}mockserver_request.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>100MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
            <maxHistory>3</maxHistory>
        </rollingPolicy>
    </appender>

    <logger name="REQUEST" level="INFO" additivity="false">
        <appender-ref ref="REQUEST_LOG"/>
    </logger>

    <logger name="org.mockserver" level="${mockserver.logLevel:-WARN}"/>
    <logger name="org.mockserver.proxy" level="${mockserver.logLevel:-INFO}"/>
    <logger name="org.mockserver.mockserver" level="${mockserver.logLevel:-INFO}"/>

    <root level="${root.logLevel:-WARN}">
        <appender-ref ref="ASYNC_FILE"/>
        <appender-ref ref="ASYNC_STDERR"/>
        <appender-ref ref="ASYNC_STDOUT"/>
    </root>
</configuration>
```

I can not see the mockserver_request.log (only the mockserver.log)

I played with the logback.xml file and when i use the following:
```
<configuration debug="false">
	<!-- request log configuration -->
	<appender name="REQUEST_LOG"
		class="org.mockserver.logging.DelayedFileCreationRollingFileAppender">
		<file>${log.dir:-./}mockserver_request.log</file>
		<encoder>
			<pattern>%msg%n</pattern>
		</encoder>

		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			<fileNamePattern>${log.dir:-./}mockserver_request.%d{yyyy-MM-dd}.%i.log
			</fileNamePattern>
			<timeBasedFileNamingAndTriggeringPolicy
				class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
				<maxFileSize>100MB</maxFileSize>
			</timeBasedFileNamingAndTriggeringPolicy>
			<maxHistory>3</maxHistory>
		</rollingPolicy>
	</appender>

	<logger name="REQUEST" level="INFO" additivity="false">
		<appender-ref ref="REQUEST_LOG" />
	</logger>

	<root level="${root.logLevel:-INFO}">
		<appender-ref ref="REQUEST_LOG" />
	</root>
</configuration>
```
I get something like that in my mockserver_request.log

```
MockServer started on port: 1080
creating expectation:

	{
	  "httpRequest" : {
	    "method" : "POST",
	    "path" : "/login"
	  },
	  "times" : {
	    "remainingTimes" : 0,
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "headers" : [ {
	      "name" : "Content-Type",
	      "values" : [ "application/json; charset=utf-8" ]
	    }, {
	      "name" : "Cache-Control",
	      "values" : [ "public, max-age=86400" ]
	    } ],
	    "body" : "{ message: 'incorrect username and password combination' }"
	  }
	}


MockServer proxy started on port: 1090 connected to remote server: localhost:1080
request:

	{
	  "method" : "POST",
	  "path" : "/login",
	  "headers" : [ {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.4.1 (Java 1.5 minimum; Java/1.6.0_45)" ]
	  }, {
	    "name" : "Host",
	    "values" : [ "localhost:1080" ]
	  }, {
	    "name" : "Accept-Encoding",
	    "values" : [ "gzip,deflate" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  }, {
	    "name" : "Connection",
	    "values" : [ "keep-alive" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}

 matched expectation:

	{
	  "method" : "POST",
	  "path" : "/login"
	}


returning response:

	{
	  "statusCode" : 200,
	  "headers" : [ {
	    "name" : "Content-Type",
	    "values" : [ "application/json; charset=utf-8" ]
	  }, {
	    "name" : "Cache-Control",
	    "values" : [ "public, max-age=86400" ]
	  } ],
	  "body" : "{ message: 'incorrect username and password combination' }"
	}

 for request:

	{
	  "method" : "POST",
	  "path" : "/login",
	  "headers" : [ {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.4.1 (Java 1.5 minimum; Java/1.6.0_45)" ]
	  }, {
	    "name" : "Host",
	    "values" : [ "localhost:1080" ]
	  }, {
	    "name" : "Accept-Encoding",
	    "values" : [ "gzip,deflate" ]
	  }, {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}


returning response:

	{
	  "statusCode" : 200,
	  "headers" : [ {
	    "name" : "Content-Length",
	    "values" : [ "58" ]
	  }, {
	    "name" : "Connection",
	    "values" : [ "keep-alive" ]
	  }, {
	    "name" : "Content-Type",
	    "values" : [ "application/json; charset=utf-8" ]
	  }, {
	    "name" : "Cache-Control",
	    "values" : [ "public, max-age=86400" ]
	  } ],
	  "body" : "{ message: 'incorrect username and password combination' }"
	}

 for request as json:

	{
	  "method" : "POST",
	  "path" : "/login",
	  "headers" : [ {
	    "name" : "Content-Length",
	    "values" : [ "0" ]
	  }, {
	    "name" : "Host",
	    "values" : [ "localhost:1090" ]
	  }, {
	    "name" : "User-Agent",
	    "values" : [ "Apache-HttpClient/4.4.1 (Java 1.5 minimum; Java/1.6.0_45)" ]
	  }, {
	    "name" : "Accept-Encoding",
	    "values" : [ "gzip,deflate" ]
	  } ],
	  "keepAlive" : true,
	  "secure" : false
	}

 as curl:

	curl -v 'http://localhost:1090/login' -X POST -H 'Content-Length: 0' -H 'Host: localhost:1090' -H 'User-Agent: Apache-HttpClient/4.4.1 (Java 1.5 minimum; Java/1.6.0_45)' -H 'Accept-Encoding: gzip,deflate' --compress
```
In mock-server website i see an example of mockserver_request.log file of the following format:
http://www.mock-server.com/proxy/record_and_replay.html
```
{
    "httpRequest": {
        "method": "POST",
        "path": "/login",
        "body": {
            "type": "STRING",
            "value": "{username: 'foo', password: 'bar'}",
        },
        "cookies": [
            {
                "name": "sid",
                "values": [ "05F1A3D2F2143C49727" ]
            }
        ],
        "headers": [
            {
                "name": "Accept-Language",
                "values": [ "en-US,en;q=0.8,fa;q=0.6" ]
            },
            {
                "name": "Cookie",
                "values": [ "sid=05F1A3D2F2143C49727" ]
            },
            {
                "name": "Host",
                "values": [ "localhost:2021" ]
            },
            {
                "name": "Content-Length",
                "values": [ "34" ]
            },
            {
                "name": "Accept-Encoding",
                "values": [ "gzip,deflate,sdch" ]
            },
            {
                "name": "User-Agent",
                "values": [ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36" ]
            },
            {
                "name": "Accept",
                "values": [ "*/*" ]
            },
            {
                "name": "Content-Type",
                "values": [ "text/plain" ]
            }
        ]
    },
    "httpResponse": {
        "statusCode": 200,
        "body": "{ message: 'success' }",
        "headers": [
            {
                "name": "Content-Type",
                "values": [ "application/json; charset=utf-8" ]
            },
            {
                "name": "Cache-Control",
                "values": [ "no-cache, no-store" ]
            }
        ]
    },
    "times": {
        "remainingTimes": 1,
        "unlimited": false
    }
}
```
How can i get the same?

**Comment by jamesdbloom** [comment] 2017-06-28 06:13
Please see the detailed code example showing how to do this in #309.

I am closing this ticket as it is a duplicate of #309 and I can not reproduce this issue.

**Closed by jamesdbloom** 2017-06-28 06:13 UTC
