### ISSUE TITLE
Response Headers Not Being Returned

### ISSUE THREAD

**Issue by sbloedel** [jamesdbloom/mockserver#630] opened 2019-05-28 19:19 UTC
I have setup the following expectation.  What I'm noticing is the mock server is returning a 200 and returning the response body.  However, the response headers are NOT being returned.

    this.mockServerClient("localhost", 1080)
      .mockAnyResponse({
        "httpRequest" : {
          "method" : "GET",
          "path" : "/api/v1/location/steve"
        },
        "httpResponse" : {
          "body" : "some_response_body",
          "headers" : {
            "steve" : [ "hello" ]
          }
        }
      }).then(
          function(result: any) {
              console.log(`Everything is looking great!! ${result}`);
          }, 
          function(error: any) {
              console.log(`There was an error: ${error}`);
          }
      );

In this case, the "steve" header is not being returned as part of the response when I call the endpoint from Postman.  However, the response body ("some_response_body") is returned correctly.

If I set it up with the via REST instead, the headers are returned appropriately.  The code below works and the 'steve' header is returned when calling from Postman
curl -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
    "httpRequest" : {
        "method" : "GET",
        "path" : "/api/v1/location/steve"
    },
    "httpResponse" : {
        "body" : "some_response_body",
        "headers" : {
          "steve" : [ "hello" ]
        }
    }
}'

Any thoughts?

**Comment by jamesdbloom** [comment] 2019-06-22 15:06
This was caused by the `mockserver-client-node` having a bug in the handling of the newer object format for headers.  This has now been fixed and pushed to the https://github.com/jamesdbloom/mockserver-client-node repo.  This will be released when I do the next release likely in around 2/3 weeks.

**Closed by jamesdbloom** 2019-06-22 15:06 UTC
