### ISSUE TITLE
Add support for simple callbacks

### ISSUE THREAD

**Issue by DariusL** [jamesdbloom/mockserver#572] opened 2018-12-20 07:48 UTC
A nice feature to have would be a the ability to register a callback on a request. This callback would not  affect behaviour and would just be a way to get request information. Something like this would be very useful to me, since I'm using mockserver as a target for webhooks and want to receive callbacks when a webhook is triggered in a JUnit test. Right now I'm using `ExpectationResponseCallback`, but that complicates things, since I can only have one active and it forces me to quickly respond inside the callback. A pure callback with no functionality attached would also let you have multiple callbacks on a single expectation registered, as far as I understand.

My idea for the API would look something like this:

```
mockServerClient.when(
                request()
                        .withMethod("POST")
                        .withPath("/post_empty"),
                Times.unlimited(),
                TimeToLive.exactly(TimeUnit.SECONDS, 10)
        ).callback(request -> {
            // assert request, put result in a future or whatever
            // no return value
}
```

**Comment by jamesdbloom** [comment] 2018-12-23 05:49
This maybe something that I will need to add when I add additional features to the UI for MockServer.

**Comment by jamesdbloom** [comment] 2019-11-16 13:54
I'm going to close this issue as a duplicate of #598 but I will look to implement post action callbacks as either a websocket callback (i.e. closure) or a remote HTTP request (i.e. web hook).

**Closed by jamesdbloom** 2019-11-16 13:54 UTC
Labels: enhancement

**Comment by priyankaa-patil** [comment] 2020-10-16 10:39
Is this feature available now?

**Comment by chepa89** [comment] 2023-03-15 13:28
@jamesdbloom : is this feature available or planned in coming time ? (callback on remote HTTP request (i.e. web hook).

**Comment by jamesdbloom** [comment] 2026-05-10 19:57
This is now supported via #2180 using the `afterActions` feature. You can register fire-and-forget callbacks (webhooks or class callbacks) that execute after the primary action completes, without affecting the response:

```json
{
  "httpRequest": { "method": "POST", "path": "/post_empty" },
  "httpResponse": { "statusCode": 200 },
  "afterActions": [{
    "httpRequest": { "method": "POST", "path": "/notification-endpoint" }
  }]
}
```
