### ISSUE TITLE
Unexpected success when path matching

### ISSUE THREAD

**Issue by ghost** [jamesdbloom/mockserver#514] opened 2018-08-18 18:58 UTC
I was writing some automated specs for our NGINX configuration and noticed that a request was matching an expectation when I thought it wasn't. I set up the expectation to match the path:

```
/api/0/applications/43d05a04-eb1d-462e-933e-3b3b4592e1c8/experiments
```

then due to a bug in my NGINX configuration I rewrote the incoming request path (that gets forwarded on to MockServer) to 

```
/api/0/applications/([0-9a-zA-Z-]+)/experiments
```

I found this behaviour confusing.  For clarity here are the logs from my test run:

```
2018-08-18 18:51:51,819 INFO o.m.m.HttpStateHandler creating expectation:

	{
	  "httpRequest" : {
	    "method" : "GET",
	    "path" : "/api/0/applications/43d05a04-eb1d-462e-933e-3b3b4592e1c8/experiments",
	    "headers" : {
	      "Content-Type" : [ "application/json" ]
	    }
	  },
	  "times" : {
	    "remainingTimes" : 1,
	    "unlimited" : false
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "headers" : {
	      "Content-Type" : [ "application/json; charset=utf-8" ],
	      "Cache-Control" : [ "no-cache, no-store" ]
	    },
	    "body" : "[{\"_id\":\"f26b3bfe-a6c2-4aa4-8376-bbba44b75ae6\",\"_applicationId\":\"43d05a04-eb1d-462e-933e-3b3b4592e1c8\",\"name\":\"You can't connect the pixel without programming the redundant RAM system!\",\"url\":\"https://jeremie.info\"}]"
	  }
	}

2018-08-18 18:51:51,837 INFO o.m.m.HttpStateHandler request:

	{
	  "method" : "GET",
	  "path" : "/api/0/applications/([0-9a-zA-Z-]+)/experiments",
	  "headers" : {
	    "content-length" : [ "0" ],
	    "Connection" : [ "close" ],
	    "User-Agent" : [ "node-superagent/3.8.2" ],
	    "Host" : [ "applications_api" ],
	    "Accept-Encoding" : [ "gzip, deflate" ],
	    "Content-Type" : [ "application/json" ]
	  },
	  "keepAlive" : false,
	  "secure" : false
	}

 matched expectation:

	{
	  "method" : "GET",
	  "path" : "/api/0/applications/43d05a04-eb1d-462e-933e-3b3b4592e1c8/experiments",
	  "headers" : {
	    "Content-Type" : [ "application/json" ]
	  }
	}

2018-08-18 18:51:51,849 INFO o.m.m.HttpStateHandler returning response:

	{
	  "statusCode" : 200,
	  "headers" : {
	    "Content-Type" : [ "application/json; charset=utf-8" ],
	    "Cache-Control" : [ "no-cache, no-store" ],
	    "connection" : [ "close" ]
	  },
	  "body" : "[{\"_id\":\"f26b3bfe-a6c2-4aa4-8376-bbba44b75ae6\",\"_applicationId\":\"43d05a04-eb1d-462e-933e-3b3b4592e1c8\",\"name\":\"You can't connect the pixel without programming the redundant RAM system!\",\"url\":\"https://jeremie.info\"}]"
	}

 for request:

	{
	  "method" : "GET",
	  "path" : "/api/0/applications/([0-9a-zA-Z-]+)/experiments",
	  "headers" : {
	    "content-length" : [ "0" ],
	    "Connection" : [ "close" ],
	    "User-Agent" : [ "node-superagent/3.8.2" ],
	    "Host" : [ "applications_api" ],
	    "Accept-Encoding" : [ "gzip, deflate" ],
	    "Content-Type" : [ "application/json" ]
	  },
	  "keepAlive" : false,
	  "secure" : false
	}

 for response action:

	{
	  "statusCode" : 200,
	  "headers" : {
	    "Content-Type" : [ "application/json; charset=utf-8" ],
	    "Cache-Control" : [ "no-cache, no-store" ]
	  },
	  "body" : "[{\"_id\":\"f26b3bfe-a6c2-4aa4-8376-bbba44b75ae6\",\"_applicationId\":\"43d05a04-eb1d-462e-933e-3b3b4592e1c8\",\"name\":\"You can't connect the pixel without programming the redundant RAM system!\",\"url\":\"https://jeremie.info\"}]"
	}

```

**Comment by jamesdbloom** [comment] 2019-11-23 08:29
This is caused by an issue where the control plane and data plane match in opposite ways.  A request coming in for the data plane is matched against a matcher.  However, a request coming in for the data plane is the matcher so the matching is in reverse.  As a result, all the matching worked both ways.  However, there have recently been some changes to enable this to no longer be correct.  I'll see if I can use those to prevent this weird/confusing behaviour.

**Comment by jamesdbloom** [comment] 2019-11-23 21:06
This is now fixed and is available in the latest SNAPSHOT version, the next release in the next few weeks will contain this fix.

**Closed by jamesdbloom** 2019-11-23 21:06 UTC
Labels: bug, next
