### ISSUE TITLE
the speed about create expectation when use callback

### ISSUE THREAD

**Issue by 53066191** [jamesdbloom/mockserver#581] opened 2019-01-11 09:30 UTC
when i create mult expecation  use callback, 
`client.when(
                request().withPath("/some/path"))
                .respond( new ExpectationResponseCallback() {
                           ...
                         }
                );
        client.when(
                request().withPath("/some/path2"))
                .respond( new ExpectationResponseCallback() {
                             ...
                          }
                );`

the server's log is :

2019-01-11 **_17:16:51_**,612 INFO o.m.m.HttpStateHandler creating expectation:

	{
	  "httpRequest" : {
	    "path" : "/some/path"
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponseObjectCallback" : {
	    "clientId" : "ffa839be-0a21-4547-8f50-819666c7b74d"
	  }
	}

2019-01-11 **_17:17:00_**,876 INFO o.m.m.HttpStateHandler creating expectation:

	{
	  "httpRequest" : {
	    "path" : "/some/path2"
	  },
	  ....
	}

2019-01-11 **_17:17:10_**,204 INFO o.m.m.HttpStateHandler creating expectation:

	{
	  "httpRequest" : {
	    "path" : "/some/path3"
	  },
	...
	}`

i feel it spend too much time

**Comment by jamesdbloom** [comment] 2019-11-12 21:05
Can you please provide more information:
- which version are you using
- how are you running it
- where are you running it
- etc.

**Comment by jamesdbloom** [comment] 2019-11-16 14:07
There have been significant performance improvements made to MockServer so it is likely this issue has now been resolved.

In addition, there have been improvements in the node client: https://github.com/jamesdbloom/mockserver-client-node/pull/39 which will shortly be released.

I am going to close this ticket as I can't reproduce this with the latest performance improvements.

**Closed by jamesdbloom** 2019-11-16 14:07 UTC
Labels: need_more_information
