### ISSUE TITLE
Possible to use regex in httpRequest.body parameters?

### ISSUE THREAD

**Issue by javascriptlove** [jamesdbloom/mockserver#268] opened 2016-07-28 11:59 UTC
Hi, i've been trying to figure out how to use regex in the `httpRequest.body.parameters` array. Is it possible like this? I can't seem to find if it is possible at all, searched through all source files

```
client.mockAnyResponse({
        'httpRequest': {
            'method': 'POST',
            'path': '/api/subscriptionPayEspago.php',
            'body': {
                'type': 'PARAMETERS',
                'parameters': [{
                    'name': 'product_id',
                    'values': ['123']
                }, {
                    'name': 'card_token',
                    'type': 'REGEX',
                    'values': ['.*']
                }]
            }
        }
...
```

Thanks

**Comment by jameskbride** [comment] 2017-09-24 12:41
Did you come up with a solution for this?  For anyone who is trying accomplish the same thing check out using "JSON Schema Body Matcher" under the [Request Matchers](http://mock-server.com/mock_server/creating_expectations.html#request_matchers) section of the documentation.  This will basically do what you're asking, even if it is a little more verbose.

**Comment by jamesdbloom** [comment] 2017-11-05 11:00
you can just use a regex as the value and it will match, so the correct syntax would be:

```
client.mockAnyResponse({
        'httpRequest': {
            'method': 'POST',
            'path': '/api/subscriptionPayEspago.php',
            'body': {
                'type': 'PARAMETERS',
                'parameters': [{
                    'name': 'product_id',
                    'values': ['123']
                }, {
                    'name': 'card_token',
                    'values': ['.*']
                }]
            }
        }
...
```

**Comment by jamesdbloom** [comment] 2017-11-05 11:02
I'm going to switch this issue to a documentation issue, as I think the only bug / enhancement required is to make the documentation clearer.

**Comment by jamesdbloom** [comment] 2017-11-15 22:02
closing as documentation element is duplicate of #115

**Closed by jamesdbloom** 2017-11-15 22:02 UTC
Labels: documentation

**Comment by glopeso** [comment] 2018-12-05 18:48
f you want to use a regex rule in a json property, you can choose to use the Json Schema that allows the use of a regex in a property pattern. Here is an example of using javascript:

```javascript
httpRequest: {
            "method": "POST",
            "path": "/user",
            "body": {
                "type": "JSON_SCHEMA",
                "jsonSchema": JSON.stringify({
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "User",
                    "description": "User data",
                    "type": "object",
                  
                    "properties": {
                        "document": {
                            "type": "string",
                            "pattern": "^9\\d{10}$"
                        },
                        "username": {
                            "type": "string"
                        }
                    }
                })
            }
        },
        httpResponse: {
            "statusCode": 202,
            "body": JSON.stringify({
                "message": "success"
            })
        }
```

**Comment by paolobiavati** [comment] 2024-04-26 12:45
> ```js
>             "body": {
>                 "type": "JSON_SCHEMA",
>                 "jsonSchema": JSON.stringify({
>                     "$schema": "http://json-schema.org/draft-04/schema#",
>                     "title": "User",
>                     "description": "User data",
>                     "type": "object",
>                   
>                     "properties": {
>                         "document": {
>                             "type": "string",
>                             "pattern": "^9\\d{10}$"
>                         },
>                         "username": {
>                             "type": "string"
>                         }
>                     }
>                 })
>             }
> ```

I couldn't get it to work... maybe it's my fault (?), but I can't find documentation for this case in 
https://mock-server.com/mock_server/creating_expectations.html#request_body_matchers
The only example with “type” : “PARAMETERS” does not use regex...

**Comment by paolobiavati** [comment] 2024-04-26 12:46
> you can just use a regex as the value and it will match, so the correct syntax would be:
> 
> ```
> client.mockAnyResponse({
>         'httpRequest': {
>             'method': 'POST',
>             'path': '/api/subscriptionPayEspago.php',
>             'body': {
>                 'type': 'PARAMETERS',
>                 'parameters': [{
>                     'name': 'product_id',
>                     'values': ['123']
>                 }, {
>                     'name': 'card_token',
>                     'values': ['.*']
>                 }]
>             }
>         }
> ...
> ```
> 
> Under the hood the parameter value and key are both matched using a case insensitive regex matcher `org.mockserver.matchers.RegexStringMatcher`.

I couldn't get it to work... maybe it's my fault (?), but I can't find documentation for this case in
https://mock-server.com/mock_server/creating_expectations.html#request_body_matchers
The only example with “type” : “PARAMETERS” does not use regex...
