### ISSUE TITLE
Documentation on how to run the sample project-mockserver-example is very minimal for a beginner

### ISSUE THREAD

**Issue by Navaneethsen** [jamesdbloom/mockserver#198] opened 2015-11-18 07:44 UTC
Hi James,

Good Day!
First of all thanks for maintaining this awesome project online.
I could easily try out a cripple of my scenarios with less effort.

I have some suggestions for improving the documentation.
I am beginner in this area of Webservice, REST, etc. I have some very basic knowledge on this area.

Basically what I was trying to do was to run the mock server in my local pc and test all the different scenarios involved in testing an already deployed RESTful web server.

All my expecations are set via ruby client code and so far I could run the basic scenarios and test as well.
I am using a software Paw to check the responses.

Some areas where I found difficult was, actually, the documentations of different techniques seem to be mixed with all the technologies. For example, there is a quote on how to set times unlimited for JAVA but i couldn't find it for RUBY, so i had to go to the code to see the available options and how to set it in ruby.

Then another major problem i faced as a beginner was how to run the mock server example project and test out different scenarios of use cases. To be more clear why I went to the mock server example was to how to understand the proxy mock server setup. Recording and playing back the requests. I dint understand much of the stuff in there.

So i googled a little bit and what i did was complied the mock server example project and started my xampp in my mac and copied the war file to the htdocs folder and tried to run it. But it wasn't working.

Another confusing problem i found was that, I installed the mock server via home-brew in my mac and everytime i run that program i see an entirely different way of starting the mock server.

![screenshot at nov 18 09-31-32](https://cloud.githubusercontent.com/assets/929451/11235118/3eb083fa-8dd7-11e5-9779-e25c02734a58.png)

I couldn't use it as per the documentation at http://www.mock-server.com/mock_server/running_mock_server.html#running_from_command_line_using_homebrew

Sorry if I am asking for something very trivial.

So If i get to make the ruby stuff working on all the scenarios, then I can help you to add some examples on how to run everything with a ruby client.

**Comment by dhina26** [comment] 2016-02-19 10:35
HI Naveen, Can you share the steps followed to run the mock server example project and test out different scenarios of use cases

**Comment by jamesdbloom** [comment] 2017-11-15 22:06
closing as duplicate of #115 which is currently in progress

**Closed by jamesdbloom** 2017-11-15 22:06 UTC
Labels: documentation
