### ISSUE TITLE
Unable to clear expectation with header that has a double negation

### ISSUE THREAD

**Issue by CC007** [jamesdbloom/mockserver#631] opened 2019-05-29 09:10 UTC
I am using Java and I have an expectation with the following httpRequest json content:

```
{
  "method" : "GET",
  "headers" : [ {
    "name" : "!mockServerContext",
    "values" : [ "!3b703d95-5492-4e37-b59c-e65688ec2b34" ]
  }, {
    "name" : "!testcase",
    "values" : [ "!testcase1" ]
  }, {
    "name" : "!action",
    "values" : [ "!action1" ]
  } ]
}
```
I found out that when I try to clear based on of the header using `withHeader(NottableString.not("mockServerContext"), NottableString.not("3b703d95-5492-4e37-b59c-e65688ec2b34")`, the expectation did not get cleared.

I even tried to clear the expectation by using `retrieveExistingExpectations(null)`, looping over them and clearing each expectation, but the expectations still didn't get cleared. 

I verified that the httpRequest of the expectations that I got were identical to the one described in the json above, so I would expect them to be cleared.

**Comment by CC007** [comment] 2019-05-29 09:33
I think this is where it goes wrong:
https://github.com/jamesdbloom/mockserver/blob/8b84fdd877e57b4eb780c9f8c8b1d65bcb448025/mockserver-core/src/main/java/org/mockserver/matchers/MultiValueMapMatcher.java#L31

**Comment by CC007** [comment] 2019-05-29 10:16
I found that if there is only one header with a negated header name and negated header value, it does work correctly, but if there are multiple headers with a negated header name and negated header value, the clear doesn't work.

**Comment by CC007** [comment] 2019-05-29 12:39
I was able to generalize the issue:

The expectation clearing breaks when the following things are true:
 - the expectation has at least one httprequest.withHeader that has a notted string for both the header name and the value;
 - the expectation has at least one httprequest.withHeader other than the one mentioned in the previous point. It doesn't matter if this header has any nottable strings.

If both conditions are met, the `MockServerClient.clear()` fails to clear the expectation.

**Comment by CC007** [comment] 2019-05-29 13:09
After debugging, the issue seems to be that this if statement causes the containsAll to be false:

https://github.com/jamesdbloom/mockserver/blob/master/mockserver-core/src/main/java/org/mockserver/collections/CaseInsensitiveRegexMultiMap.java#L50-L51

**Comment by CC007** [comment] 2019-05-29 13:31
I think that if you change:
```
if ((entry.getKey().isNot() || entry.getValue().isNot()) && containsKeyValue(entry.getKey().getValue(), entry.getValue().getValue())) {
```
to 
```
if ((entry.getKey().isNot() || entry.getValue().isNot()) && !(entry.getKey().isNot() && entry.getValue().isNot()) && containsKeyValue(entry.getKey().getValue(), entry.getValue().getValue())) {
```
This issue is fixed. 
I am unable to provide a pull request from my current workstation.

**Comment by jamesdbloom** [comment] 2019-06-01 05:02
Ok thanks for that very detailed bug report and debugging I'll look into fixing this

**Comment by jamesdbloom** [comment] 2019-06-01 06:49
I'm working on fixing this issue I agree the problem is with the if condition.  I've added some tests that fail and illustrate the bug you raised.

Unfortunately I don't with the suggestion about the XOR.  The Key and Value should be XORed because they are totally unrelated.  

The existing simple approach of just checking if the header is notted doesn't work either (thus the bug you raised).  The problem is that this works perfectly for matching against incoming requests (when responding to an expectation - i.e. data plane).  However this same logic is also used to match against incoming request matchers (when clearing, retrieving, resetting - i.e. control plane).  In the control plane scenarios an incoming request matcher with a not should be matched against an existing expectation which a request matcher with a not, but currently it isn't.  I think the problem is exactly where you pointed out in first part of the if statement.  This shouldn't be here and this logic should be pushed down into the containsKeyValue function which should return true if both side of the match contain the same notted key and value.  I'll try to fix this.

**Comment by CC007** [comment] 2019-06-01 10:59
You're right. I already thought it to be weird that for clearing the request doesn't get matched literally.

**Comment by jamesdbloom** [comment] 2019-06-01 13:36
The problem is you can't match the request literally, because the clear function for example works with the request logs.  If I relied on a literal match then it would be very difficult to clear the logs because you'd need to know exact what request was sent.  I think I have a nice approach boiled down the RegexStringMatcher.  Ultimately no real request will come in with anything notted, so I'm used that fact to make both cases work.  Also without anything notted the logic already works.

**Comment by jamesdbloom** [comment] 2019-06-02 06:12
This bug is now fixed and is available in the latest SNAPSHOT version.

**Closed by jamesdbloom** 2019-06-02 06:12 UTC

**Comment by CC007** [comment] 2019-06-18 09:10
When will this version be released?

**Comment by jamesdbloom** [comment] 2019-06-18 09:24
This will be released on the 23rd at the latest but likely on 21st.
