### ISSUE TITLE
mockserver-maven-plugin:5.2.3:start results to java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1

### ISSUE THREAD

**Issue by franz-see** [jamesdbloom/mockserver#399] opened 2017-12-19 13:06 UTC
Given POM

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ph.net.ph</groupId>
    <artifactId>mock-server-trial</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>mock-server-trial</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>5.2.3</version> <!-- build error -->
                <!--<version>3.11</version>--> <!-- works -->
                <configuration>
                    <serverPort>1080</serverPort>
                    <proxyPort>1090</proxyPort>
                    <logLevel>DEBUG</logLevel>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

And command `mvn mockserver:start -X`

I expect mockserver to start.

But I got 

```
$ mvn mockserver:start -X
...
Exception in thread "nioEventLoopGroup-2-5" java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$1
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

[mockserver-start-build.log](https://github.com/jamesdbloom/mockserver/files/1571717/mockserver-start-build.log)

**Comment by jamesdbloom** [comment] 2017-12-20 06:27
I can reproduce the issue and I am looking into why this is happening.

**Comment by jamesdbloom** [comment] 2017-12-20 06:49
The only difference with version 3.11 in this respect is the netty dependency has been upgraded.  It looks like they are doing something very strange and non standard with the way they are now managing their maven structure.  I'm trying to look into this to resolve this issue and why maven transitive dependencies are no longer being correctly pulled into the plugin.

**Comment by jamesdbloom** [comment] 2017-12-20 15:26
This is not a bug or issue.  Instead this problem is caused by Netty attempting to shutdown after the classpath provided by maven is no longer available, in the following code:

```java
java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannel$AbstractUnsafe$8
	at io.netty.channel.AbstractChannel$AbstractUnsafe.deregister(AbstractChannel.java:813)
```

at

```java
// As a user may call deregister() from within any method while doing processing in the ChannelPipeline,
// we need to ensure we do the actual deregister operation later. This is needed as for example,
// we may be in the ByteToMessageDecoder.callDecode(...) method and so still try to do processing in
// the old EventLoop while the user already registered the Channel to a new EventLoop. Without delay,
// the deregister operation this could lead to have a handler invoked by different EventLoop and so
// threads.
//
// See:
// https://github.com/netty/netty/issues/4435
invokeLater(new Runnable() {
    @Override
    public void run() {
        try {
            doDeregister();
        } catch (Throwable t) {
            logger.warn("Unexpected exception occurred while deregistering a channel.", t);
        } finally {
            if (fireChannelInactive) {
                pipeline.fireChannelInactive();
            }
            // Some transports like local and AIO does not allow the deregistration of
            // an open channel.  Their doDeregister() calls close(). Consequently,
            // close() calls deregister() again - no need to fire channelUnregistered, so check
            // if it was registered.
            if (registered) {
                registered = false;
                pipeline.fireChannelUnregistered();
            }
            safeSetSuccess(promise);
        }
    }
}); 
```

This is an issue because MockServer has not received a single request before it is attempted to be shutdown and that causes a problem with Netty if the classpath is no longer available.

If you add a single test to you example project as follows:

```java
import org.junit.Test;

import java.net.HttpURLConnection;
import java.net.URL;

public class TestDelay {

    @Test
    public void testDelay() throws Exception {
        HttpURLConnection connection = (HttpURLConnection) new URL("http://localhost:1080/").openConnection();
        connection.setRequestMethod("GET");
        System.out.println("connection.getResponseCode() = " + connection.getResponseCode());
        System.out.println("connection.getResponseMessage() = " + connection.getResponseMessage());
    }
}
```
and run the follow:

```bash
mvn install
```

Then you don't get the error with 5.2.3, so I am closing this issue because its not a bug.

**Closed by jamesdbloom** 2017-12-20 15:26 UTC
Labels: bug, invalid

**Comment by franz-see** [comment] 2017-12-24 13:38
This is a bug because it crashes with an unhelpful error message/stack instead of behaving as expected - either it executed properly or states what the problem is.

In this case, a simple error message stating that it cannot run without a single test would have sufficed.

Either that, it shutsdown gracefully without error.

Im willing to contribute if you can point me to the right direction

**Comment by jamesdbloom** [comment] 2017-12-25 11:11
It is not a bug because this is 100% caused by Maven removing the classpath which is completely beyond my control and just the way maven works.  

The plugin is not intended to work like this and is not documented to work like this.  It doesn't even make sense to run MockServer within maven then immediately stop it because the maven build has finished.

If it is used as it not intended then there will be errors.  If you want to run the plugin in this fashion use the `runForked` command.

In addition there is no mechanism within Maven for me to even detect that this is being used in this way so there would be no way or warning users that there where using the plugin this way.  I can only do what Maven allows me to do in a Maven plugin.
