### ISSUE TITLE
Proxy SSLException: Unrecognized SSL message 

### ISSUE THREAD

**Issue by AndreTheHunter** [jamesdbloom/mockserver#277] opened 2016-08-25 07:25 UTC
I keep getting `io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?` error when running my tests.

I start the proxy:

``` shell
java -Dmockserver.logLevel=DEBUG -jar mockserver.jar -proxyPort 1090 -serverPort 1080
```

I start the app:

``` shell
java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=1090 -jar myapp.jar
```

The test tells the proxy to dump all the requests to the log:

``` js
require('mockserver-client').proxyClient('localhost', 1080).dumpToLogs()
```

The test runs and produces the error. See the MockServer and app logs below. I've also included my proxy client class (ProxySelector).

What am I doing wrong? Please help

mockserver.log:

```
2016-08-25 07:07:34,869 DEBUG [nioEventLoopGroup-5-2] org.mockserver.socket.SSLFactory [?:?] Using protocol TLSv1.2
2016-08-25 07:07:35,026 WARN [nioEventLoopGroup-5-2] o.m.proxy.relay.RelayConnectHandler [?:?] Exception caught by upstream relay handler -> closing pipeline [id: 0x105d8494, /10.0.2.15:56208 :> /10.0.2.15:1090]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400) ~[mockserver.jar:na]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) ~[mockserver.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver.jar:na]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [mockserver.jar:na]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [mockserver.jar:na]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_91]
    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_91]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) ~[mockserver.jar:na]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976) ~[mockserver.jar:na]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912) ~[mockserver.jar:na]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369) ~[mockserver.jar:na]
    ... 12 common frames omitted
2016-08-25 07:07:35,057 WARN [nioEventLoopGroup-5-1] o.m.p.u.PortUnificationHandler [?:?] Exception caught by port unification handler -> closing pipeline [id: 0x2036c4ec, /10.0.2.15:56209 :> 0.0.0.0/0.0.0.0:1090]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400) ~[mockserver.jar:na]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) ~[mockserver.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [mockserver.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [mockserver.jar:na]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) [mockserver.jar:na]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver.jar:na]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [mockserver.jar:na]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: javax.net.ssl.SSLException: Received close_notify during handshake
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1776) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[na:1.8.0_91]
    at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_91]
    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_91]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) ~[mockserver.jar:na]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976) ~[mockserver.jar:na]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912) ~[mockserver.jar:na]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369) ~[mockserver.jar:na]
    ... 12 common frames omitted
```

myapp log:

```
! java.io.EOFException: SSL peer shut down incorrectly
! at sun.security.ssl.InputRecord.read(InputRecord.java:505)
! at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
! ... 86 common frames omitted
! Causing: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
! at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
! at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
! at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
! at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
! at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:573)
! at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:447)
! at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:219)
! at org.apache.http.impl.conn.ManagedClientConnectionImpl.layerProtocol(ManagedClientConnectionImpl.java:421)
! at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:815)
! at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:616)
! at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
! at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
! at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:78)
! at com.microtripit.mandrillapp.lutung.controller.MandrillUtil.query(MandrillUtil.java:46)
! at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.sendTemplate(MandrillMessagesApi.java:206)
! at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.sendTemplate(MandrillMessagesApi.java:133)
! at au.com.jesims.email.MandrillEmailClient.sendMessage(MandrillEmailClient.java:392)
```

Proxy client class

``` java
public final class MockServerProxySelector extends ProxySelector {
    private static final Logger log = getLogger(MockServerProxySelector.class);

    public static void setup() {
        setDefault(new MockServerProxySelector());
    }

    @Override
    public List<Proxy> select(final URI uri) {
        List<Proxy> proxies = emptyList();
        final int port = uri.getPort();
        final int databasePort = Integer.valueOf(System.getenv("DATABASE_PORT"));
        if (notEquals(port, databasePort)) {
            final Proxy proxy = createProxy();
            if (nonNull(proxy)) {
                proxies = singletonList(proxy);
            }
        }
        return proxies;
    }

    private static @Nullable Proxy createProxy() {
        final String host = System.getProperty("http.proxyHost");
        final String port = System.getProperty("http.proxyPort");
        Proxy proxy = null;
        if (isNotEmpty(host) && isNotEmpty(port)) {
            final InetSocketAddress address = new InetSocketAddress(host, Integer.parseInt(port));
            proxy = new Proxy(SOCKS, address);
        } else {
            log.info("Proxy not defined");
        }
        return proxy;
    }

    @Override
    public void connectFailed(final URI uri, final SocketAddress sa, final IOException ioe) {
        final String msg = String.format("Connection could not be established to proxy at socket [%s]", sa);
        log.error(msg, ioe);
    }
}
```

I downloaded the proxy using:

```
mockserver_version=3.10.4
url=http://search.maven.org/remotecontent?filepath=org/mock-server/mockserver-netty/${mockserver_version}/mockserver-netty-${mockserver_version}-jar-with-dependencies.
wget --output-document=mockserver.jar ${url}
```

**Comment by jamesdbloom** [comment] 2016-10-15 08:24
When does this error occur?  It is after the test has finished running completely or in the middle?

It looks clearly like during the SSL handshake some non SSL traffic was received.  

Are you trying to send SSL traffic and conscientiously using SOCKS?

It would be helpful to see some more of the code, ideally enough so I could run the same or a similar example myself.

**Comment by jamesdbloom** [comment] 2017-06-28 05:26
The the SSL logic has been significantly improved in the latest release version 3.10.8. I am now closing this issue because I believe that release has fixed the issue.  If the issue is still present in that release please re-open this issue.

**Closed by jamesdbloom** 2017-06-28 05:26 UTC
Labels: question

**Comment by maulidailham** [comment] 2023-10-24 04:45
this issue need to be reopened on recent update, this issue just resurfaced
