### ISSUE TITLE
Verifying Proxy-Authorization Header

### ISSUE THREAD

**Issue by alexsm82** [jamesdbloom/mockserver#348] opened 2017-06-22 22:35 UTC
I am hoping to use the Junit verify functionality to test that a Proxy-Authorization header is correctly added to my request.  However, the Proxy-Authorization header is stripped from the request before the verification takes place.  It seems like a better flow would be to record the request with all the headers for verification, then remove the headers that will not be passed on. 

I've been playing around with this locally and would be happy to create a PR based on your feedback.

**Comment by 2082** [comment] 2017-06-27 07:47
This would be possible it would likely require mapping hop-by-hop headers into a request when it gets converted from a Netty request into a MockServer request then removing these hop-by-hop requests before this request is forwarded. From memory I believe in the current approach they are not mapped from the Netty request so they don't get recorded. From memory the correct place to remove the headers would be HttpProxyHandler probably in using a request filter.

I can't see the code at the moment so this may be slightly wrong but i don't think it shouldn't be too hard to do. I can certainly take a look or if you would like to submit a PR that would also work.

**Comment by jamesdbloom** [comment] 2017-06-27 09:09
Actually it seems like the cause of the problem is that the HopByHopHeaderFilter doesn't clone the request.  So when it removes the hop-by-hop requests they are remove from the request.  In addition the recorded of request can't happen until after the response has been received.  There is a fix for this but it requires slightly refactoring the way the request is sent and may have other side effect.  Partly because the RequestFilters can completely remove a request from the pipeline by returning `null`.

All of this means the solution is not immediately straight forward but still doable.

**Comment by jamesdbloom** [comment] 2017-06-28 05:16
This should now be fixed but has not yet been released. To be able to take advantage of this before the next release you could use the latest SNAPSHOT version.

**Closed by jamesdbloom** 2017-06-28 05:16 UTC

**Comment by alexsm82** [comment] 2017-06-29 14:52
@jamesdbloom Any idea when the next release will be?

**Comment by jamesdbloom** [comment] 2017-06-29 16:07
The next release will be in the next 2/3 days once I have completed some
work on JSON Schema validation for the REST API.

**Comment by alexsm82** [comment] 2017-06-29 18:43
Sounds good, thanks!

**Comment by alexsm82** [comment] 2017-08-28 22:25
Hey @jamesdbloom, any update for when we can expect the next release?  Thanks!
