### ISSUE TITLE
not enough simple documentation available

### ISSUE THREAD

**Issue by firecentaur** [jamesdbloom/mockserver#379] opened 2017-11-07 06:21 UTC
Hi James, 

Your software looks really promising.  We want to use it to record all backend responses.
We have successfully set up a docker image of mocker server.

But now what?
I can't find any documentation on what to do after the docker image is installed.  How can I use this docker image to record all backend responses from my frontend api?

**Comment by jamesdbloom** [comment] 2017-11-07 06:30
You can use the MockServer as a reverse proxy to generate expectations for backend responses.

Record-reply is not supported because this is an anti pattern for testing.  Record-reply breaks encapsulation, single responsibility principle and separation of concerns because the mock for a test is completely separate from the test and shared by all tests.  This approach typically results in tests that are much more expensive and complex to maintain.  

The equivalent in MockServer is to use the proxy to reserve proxy all calls from your frontend to your backend.  Then you can dump all recorded request / responses to a log file in expectation format.  This allows you to copy and paste those expectations into your tests.  When you copy the expectations it is also recommended to simplify them because MockServer will record all headers and everything when typically test only needs the relevant headers, queries parameters, body, etc that is important for that test.

Does that make sense?

**Comment by jamesdbloom** [comment] 2017-11-15 21:58
closing as a duplicate of #115

**Closed by jamesdbloom** 2017-11-15 21:58 UTC
Labels: documentation
