### ISSUE TITLE
Does mockserver support socket?

### ISSUE THREAD

**Issue by benhuangyong** [jamesdbloom/mockserver#413] opened 2018-01-15 14:56 UTC
I cant't get any information from document  and examples.

**Comment by jamesdbloom** [comment] 2018-01-15 19:18
I assume you mean Web Sockets?

MockServer doesn't currently support Web Sockets, however it is on the list of new feature that will be implemented, likely in the next few months.

This issue is a duplicate of #360 so I'm going to close it, but please monitor that issue for progress on implementing Web Socket mocking support.  Once the work on the UI is completed then the next feature to be implement will be Web Socket support.

**Closed by jamesdbloom** 2018-01-15 19:18 UTC
