### ISSUE TITLE
Ability to support protobufs

### ISSUE THREAD

**Issue by tvsathish** [jamesdbloom/mockserver#265] opened 2016-07-22 11:27 UTC
Hi,
   Actually this is a feature request but did not find a category for the same. Can this project be please extended to identify and use PROTOBUF messages - would be great to use in mobile app automation testing to mock requests from the app?

Thanks,
Sathish

**Comment by jamesdbloom** [comment] 2019-11-16 13:16
duplicate of #682

**Closed by jamesdbloom** 2019-11-16 13:16 UTC
Labels: enhancement, proposal
