### ISSUE TITLE
callbacks fail when invoked in parallel

### ISSUE THREAD

**Issue by jarekczek** [jamesdbloom/mockserver#466] opened 2018-05-02 21:33 UTC
I tried to put some stress on mock-server and noticed it fails as soon as 2 requests come in the same time. I didn't see the issue when mock-server returned plain response. But it happens when mock-server returns a response through callback.

Logs show, that mock-server "is returning" 2 answers. The first client receives the answer. However the second client doesn't get any byte in its http connection. It times out on socket read.

I demonstrate the issue in a simple project: https://github.com/jarekczek/simpleMockServer/tree/master/bug-report

mock-server looks great for my purpose. I can use it successfully even now, but I need fully functional callbacks to accomplish all the goals. I hope we will be able to fix it. Thank you James for this useful software.

**Comment by jarekczek** [comment] 2018-05-02 22:19
Seems like the issue is gone in 5.3.1-SNAPSHOT. So I'll just wait for a release. Thank you and looking forward to 5.3.1.

**Comment by jamesdbloom** [comment] 2018-11-14 06:36
this issue is now resolved and released the fix is in both 5.3.0 and 5.4.1

**Closed by jamesdbloom** 2018-11-14 06:36 UTC

**Comment by lchayoun** [comment] 2019-02-23 18:46
@jamesbloomnektan the issue seems to be resolved using version 5.4.1 but the issue is back since 5.5.0
