### ISSUE TITLE
Expectation response Content-Type not honoured when actual response returned (regression 3.9.16+)

### ISSUE THREAD

**Issue by adammichalik** [jamesdbloom/mockserver#163] opened 2015-08-05 10:17 UTC
Works fine with 3.9.15, breaks with 3.9.16 and 3.9.17.

Given a following expectation:
```javascript
{
    "httpRequest": {
        "method": "GET",
        "path": "/test"
    },
    "httpResponse": {
        "statusCode": 200,
        "headers": [
            {
                "name": "Content-Type",
                "values": ["text/xml"]
            }
        ],
        "body": "<test>Hello world</test>"
    }
}
```
I expect the MockServer response to have Content-Type header `text/xml`.

For 3.9.15 that is the case. However, 3.9.16 and .17 return the response with `Content-Type: text/plain`. Setting the Accept header of the request does not influence that - still `text/plain` is returned. Other than that, the body is returned correctly.

**Comment by jamesdbloom** [comment] 2015-08-05 10:29
As soon as I get a chance I'll look into this, likely in the next week, but it definitely sounds like a bug as the Content-Type head logic was improved recently.  Clearly a bug was introduced.

**Comment by adammichalik** [comment] 2015-08-05 10:54
Thanks, James! MockServer has been helping us greately with mocking of SOAP backends, but our SOAP consumer framework explicitly expects the response to come as text/xml.

**Comment by jamesdbloom** [comment] 2015-08-05 11:25
I can't reproduce this bug.  When I submit an expectation using the JSON you provided I get a response with the correct Content-Type header as follows:

JSON Expectation

```json
{
    "httpRequest": {
        "method": "GET",
        "path": "/test"
    },
    "httpResponse": {
        "statusCode": 200,
        "headers": [
            {
                "name": "Content-Type",
                "values": ["text/xml"]
            }
        ],
        "body": "<test>Hello world</test>"
    }
}
```

Submit expectation using curl:

```bash
$ curl -v 'http://localhost:1080/expectation' -X PUT -d '{
    "httpRequest": {
        "method": "GET",
        "path": "/test"
    },
    "httpResponse": {
        "statusCode": 200,
        "headers": [
            {
                "name": "Content-Type",
                "values": ["text/xml"]
            }
        ],
        "body": "<test>Hello world</test>"
    }
}' -H "Content-Type: application/json"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 1080 (#0)
> PUT /expectation HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:1080
> Accept: */*
> Content-Type: application/json
> Content-Length: 317
> 
* upload completely sent off: 317 out of 317 bytes
< HTTP/1.1 201 Created
< Content-Length: 0
< Connection: keep-alive
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
```

Test expectation using curl:

```bash
$ curl -v http://localhost:1080/test
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 1080 (#0)
> GET /test HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:1080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/xml
< Content-Length: 24
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
<test>Hello world</test>
```

Notice the response has the header `Content-Type: text/xml`.

Please re-test and provide me with more feedback.

Thanks,

James

**Comment by jamesdbloom** [comment] 2015-08-05 11:27
I am however using the latest SNAPSHOT version, but I don't believe any of this code changed in the latest version.  If possible I would be grateful if you could try the same test on the latest SNAPSHOT version.  For information on how to find this please see: http://www.mock-server.com/where/maven_central.html#sonatype_snapshot

**Comment by adammichalik** [comment] 2015-08-05 11:47
I checked the 3.9.18-SNAPSHOT WAR from Sonatype Nexus, dated as `mockserver-war-3.9.18-20150712.133012-20`.

I used the same commands as you did, but I'm still getting text/plain.

```
$ curl -v 'http://localhost:8080/mockserver-war-3.9.18-20150712.133012-20/expectation' -X PUT -d '{
    "httpRequest": {
        "method": "GET",
        "path": "/test"
    },
    "httpResponse": {
        "statusCode": 200,
        "headers": [
            {
                "name": "Content-Type",
                "values": ["text/xml"]
            }
        ],
        "body": "<test>Hello world</test>"
    }
}' -H "Content-Type: application/json"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> PUT /mockserver-war-3.9.18-20150712.133012-20/expectation HTTP/1.1
> User-Agent: curl/7.41.0
> Host: localhost:8080
> Accept: */*
> Content-Type: application/json
> Content-Length: 317
>
* upload completely sent off: 317 out of 317 bytes
< HTTP/1.1 201 Created
< Server: Apache-Coyote/1.1
< Content-Length: 0
< Date: Wed, 05 Aug 2015 11:38:59 GMT
<
* Connection #0 to host localhost left intact
```
```
$ curl -v http://localhost:8080/mockserver-war-3.9.18-20150712.133012-20/test
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /mockserver-war-3.9.18-20150712.133012-20/test HTTP/1.1
> User-Agent: curl/7.41.0
> Host: localhost:8080
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: text/plain
< Content-Length: 24
< Date: Wed, 05 Aug 2015 11:39:38 GMT
<
<test>Hello world</test>* Connection #0 to host localhost left intact
```

I'm running Tomcat 7.0.61 with JDK 7u79 64bit on Windows 7 64bit. I used Curl from GitBash console. I deployed MockServer by dropping the WAR into Tomcat's webapps.

What can I do to help?

**Comment by jamesdbloom** [comment] 2015-08-05 11:51
Arh you're using the WAR, I was testing with the Netty version.  I'll check the WAR and get back to you tomorrow.

**Comment by jamesdbloom** [comment] 2015-08-05 11:52
Most of the code is shared accept the very top level of integration in Netty or JEE and that is where the Content-Type header defaulting is handled.  I guess its not correctly detecting that you have already set a Content-Type header so it is overriding your head with the default one.

**Comment by jamesdbloom** [comment] 2015-08-05 12:12
I've found the issue but I need to add a test and fix it before I can submit this fix.

**Comment by adammichalik** [comment] 2015-08-05 12:16
Awesome, thanks in advance!

2015-08-05 14:12 GMT+02:00 James D Bloom <notifications@github.com>:

**Comment by jamesdbloom** [comment] 2015-08-05 16:50
I have now fixed this issue

**Closed by jamesdbloom** 2015-08-05 16:50 UTC

**Comment by adammichalik** [comment] 2015-08-06 07:04
Thanks! Looking forward to the next release!

**Comment by jamesdbloom** [comment] 2015-08-27 08:07
Sorry for the delay I didn't manage to do the release before leaving London for a few weeks, I'll be doing one on the next couple of days once I've looked into 1 minor bug

**Comment by mherz** [comment] 2015-09-17 13:31
Any clue when the fix will be released?

**Comment by jamesdbloom** [comment] 2015-09-20 20:29
I'm realising it right now, it'll be on Maven Central in the next couple of hours (once its updated)
