### ISSUE TITLE
httpForward swallowing all requests

### ISSUE THREAD

**Issue by AndySeymour** [jamesdbloom/mockserver#295] opened 2016-11-02 14:29 UTC
I'm configuring a mockserver to forward all requests and then trying to set one specific path to respond with a mock. Unfortunately, it seems like the forwarder swallows all the requests. Below is the configuration code:

```
var mockserver = require('mockserver-grunt');
var mockServerClient = require('mockserver-client').mockServerClient;
var HTTP_PORT = 1080;
```
```
mockserver.start_mockserver({
        serverPort: HTTP_PORT
    }).then(function(){

        mockServerClient("localhost", HTTP_PORT).mockAnyResponse({
	  "httpRequest": {
	        "path": "/.*"
	    },
	   "httpForward": {
	        "host": "127.0.0.1",
	        "port": 8080,
	        "scheme": "HTTP"
	    },
	    "times": {
	        "unlimited": true
	    }
	})

        mockServerClient("localhost", HTTP_PORT).mockAnyResponse({
          "httpRequest": {
              "path": "/andy/andy",
              "method": "GET"
          },
          "httpResponse": {
              "statusCode": 200,
              "headers": [{
                  "name": "Content-Type",
                  "values": ["application/json;charset=UTF-8"]
              }],
              "body": JSON.stringify({"andy":"test"})
           },
           "times": {
              "unlimited": true
           }
         })
    });
```
`console.log("started on port: " + HTTP_PORT);`

**Comment by jamesdbloom** [comment] 2016-11-09 09:56
This is expected behaviour because you have added an expectation that matches on all requests first.  If you swap the order of the expectations then you should get the result you need, as follows:

```js
mockserver.start_mockserver({
    serverPort: HTTP_PORT
}).then(function () {

    mockServerClient("localhost", HTTP_PORT).mockAnyResponse({
        "httpRequest": {
            "path": "/andy/andy",
            "method": "GET"
        },
        "httpResponse": {
            "statusCode": 200,
            "headers": [{
                "name": "Content-Type",
                "values": ["application/json;charset=UTF-8"]
            }],
            "body": JSON.stringify({"andy": "test"})
        },
        "times": {
            "unlimited": true
        }
    });

    mockServerClient("localhost", HTTP_PORT).mockAnyResponse({
        "httpRequest": {
            "path": "/.*"
        },
        "httpForward": {
            "host": "127.0.0.1",
            "port": 8080,
            "scheme": "HTTP"
        },
        "times": {
            "unlimited": true
        }
    });
});
```

The key point is that expectation are matched in the order they are added (as long as they are still valid).

**Comment by jamesdbloom** [comment] 2016-11-09 09:57
I'm going to close this issue but please re-open if this doesn't work for you.

**Closed by jamesdbloom** 2016-11-09 09:57 UTC

**Comment by AndySeymour** [comment] 2016-11-09 11:32
@jamesdbloom So my implementation involves setting up a bunch of micro-services and putting a mockserver in front of all of them. In the test setup, I would simply forward all requests through to the micro-service. The tests can then change this behaviour to mock certain requests. A test will use a unique cookie to define requests and then we can clear all expectations which have that unique cookie at the end (test cleanup).

Is this a worthwhile enhancement and something you'd accept in a PR?
