### ISSUE TITLE
Expectation to generate chunked transfer-encoding data from mockserver?

### ISSUE THREAD

**Issue by avmohan** [jamesdbloom/mockserver#355] opened 2017-07-07 03:07 UTC
Hi, is there a way to set the expectations such that the response generated by mockserver has chunked transfer-encoding?

**Comment by smitadas** [comment] 2017-10-26 17:33
@avmohan I am looking for the same. Did you find a solution?

**Comment by avmohan** [comment] 2017-10-27 04:26
I didn't actually. Not sure, but I don't think mockserver supports the same as it's more focussed on the higher level aspects and transfer encoding is a bit lower level for this. I ended up using an embedded http server for mocking chunked response. - https://hc.apache.org/httpcomponents-core-4.4.x/tutorial/html/blocking-io.html#d5e460

**Comment by jamesdbloom** [comment] 2017-11-16 07:16
It could be technically possible to do this, the main issue is that the current design works on a complete request / response body.  Netty fairly easily supports this but the issue is that it requires using slightly different interfaces `HttpResponse` instead of `FullHttpResponse`.

I'll mark this as an enhancement and try to implement it once other issues on updating the MockServer documentation has been completed.

**Comment by jamesdbloom** [comment] 2019-11-22 16:49
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/lTBN3na9/18-response-with-chunked-transfer-encoding-data

**Closed by jamesdbloom** 2019-11-22 16:49 UTC
Labels: enhancement
