### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by davidrodriguezrodero** [jamesdbloom/mockserver#319] opened 2017-03-08 00:20 UTC
Running MockServer using Maven plugin

                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>3.10.4</version>
When using MockServer Proxy the generated file certificates are expired already.
Expires on 08/02/17

Thank for your brilliant tool!!

**Comment by jamesdbloom** [comment] 2017-05-07 20:31
Perhaps you could try updating you version of MockServer to the latest version.

The current version has a root certificate expiring in year 2116.

<img width="474" alt="screen shot 2017-05-07 at 21 26 18" src="https://cloud.githubusercontent.com/assets/733179/25784844/de05518e-336b-11e7-8833-1171961c041a.png">

And a dynamic certificate for each domain expiring in year 2117

<img width="476" alt="screen shot 2017-05-07 at 21 26 11" src="https://cloud.githubusercontent.com/assets/733179/25784845/de07af4c-336b-11e7-92be-a661ea4db577.png">

I'm closing this ticket because I think you issue is caused by an out of date version of MockServer and this issue was already fixed #156.

**Closed by jamesdbloom** 2017-05-07 20:31 UTC
